"""The frame around a generated document: header, body digest, size cap, truncation.

A generated file is ``header + blank line + body``::

    <!-- ddflow:generated doc=roadmap v=0.1.9 body-sha256=0123456789ab -->
    Generated by ddflow from the event log - edit the source, not this file

    <body>

The digest covers the BODY text only (everything after the first blank line), never the
log: a log digest is stale the moment any event lands, while a body digest says exactly
one thing -- "has anyone edited this file since ddflow wrote it?". That is the hand-edit
test the writer (B-export-write) and ``--check`` rely on. Optional extra header attributes
(``last=<event id>`` for append-only documents) are written sorted, after the digest.

Nothing here reads the clock: the same body yields the same bytes.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from ... import FORMAT_LEVEL
from ...core.digest import content_digest
from ...core.events import is_older
from ...infra.fsio import parse_level

#: Second header line. Fixed text.
NOTICE = "Generated by ddflow from the event log - edit the source, not this file"

#: stdout cap. ``--max-bytes`` overrides; 0 means no cap (what a file write uses).
DEFAULT_MAX_BYTES = 60_000

DIGEST_LEN = 12

#: The format level of every header written before ``fmt=`` existed: an absent ``fmt`` means
#: this, and a header at this level does not spell it, so a document ddflow regenerates is
#: byte for byte what it was (the goldens stay put). A higher level is written as ``fmt=N``.
IMPLICIT_FMT = 1

_HEADER_RE = re.compile(
    r"^<!-- ddflow:generated doc=(?P<doc>[A-Za-z0-9_.-]+) v=(?P<v>\S+) "
    rf"body-sha256=(?P<sha>[0-9a-f]{{{DIGEST_LEN}}})(?P<extra>(?: [A-Za-z0-9_-]+=\S+)*) -->$"
)


@dataclass(frozen=True)
class Header:
    doc: str
    version: str
    digest: str
    extra: dict[str, str] = field(default_factory=dict)
    #: The writer's FORMAT_LEVEL (docs/ddflow/compatibility.md). Not part of ``extra``.
    fmt: int = IMPLICIT_FMT

    def line(self) -> str:
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", self.doc) or not re.fullmatch(r"\S+", self.version):
            raise ValueError(f"header doc={self.doc!r} v={self.version!r} is not representable")
        for k, v in self.extra.items():
            # What `split` can read back: anything else would write a header ddflow itself
            # fails to parse, and hand-edit protection would silently see "not ours".
            if not re.fullmatch(r"[A-Za-z0-9_-]+", str(k)) or not re.fullmatch(r"\S+", str(v)):
                raise ValueError(f"header attribute {k}={v!r} is not representable")
        attrs = dict(self.extra)
        if self.fmt != IMPLICIT_FMT:
            attrs["fmt"] = str(self.fmt)
        extra = "".join(f" {k}={v}" for k, v in sorted(attrs.items()))
        return (
            f"<!-- ddflow:generated doc={self.doc} v={self.version} "
            f"body-sha256={self.digest}{extra} -->"
        )


def body_digest(body: str) -> str:
    """The first ``DIGEST_LEN`` hex chars of sha256 over the body's UTF-8 bytes."""
    return content_digest(body, length=DIGEST_LEN)


def normalize(body: str) -> str:
    """Exactly one trailing newline. Applied before digesting so a template's trailing
    blank lines cannot make two equal documents differ."""
    return body.rstrip("\n") + "\n"


def newer(head: Header, fmt: int | None = None) -> bool:
    """True when the header was written at a higher format level than ``fmt`` (this ddflow's)."""
    return head.fmt > (FORMAT_LEVEL if fmt is None else fmt)


def frame(
    body: str,
    doc: str,
    version: str,
    extra: dict[str, str] | None = None,
    fmt: int | None = None,
) -> str:
    """Header + notice + blank line + normalized body. Deterministic."""
    body = normalize(body)
    head = Header(
        doc, version, body_digest(body), dict(extra or {}), FORMAT_LEVEL if fmt is None else fmt
    )
    return f"{head.line()}\n{NOTICE}\n\n{body}"


def split(text: str) -> tuple[Header | None, str]:
    """``(header, body)`` of a generated file; ``(None, text)`` if it carries no header.

    The body is what follows the notice line and one blank line, byte for byte.
    """
    first, _, rest = text.partition("\n")
    m = _HEADER_RE.match(first)
    if not m:
        return None, text
    notice, _, after = rest.partition("\n")
    if notice != NOTICE or not after.startswith("\n"):
        return None, text
    extra = {}
    for pair in m.group("extra").split():
        k, _, v = pair.partition("=")
        extra[k] = v
    fmt = IMPLICIT_FMT
    level = parse_level(extra.get("fmt", ""))
    if level is not None:  # anything else stays an unknown attribute
        fmt = level
        del extra["fmt"]
    return Header(m.group("doc"), m.group("v"), m.group("sha"), extra, fmt), after[1:]


def hand_edited(text: str) -> bool | None:
    """True if a generated file's body no longer matches its header digest, False if it
    does, None if the text has no ddflow header (an unmarked file is not ours)."""
    head, body = split(text)
    if head is None:
        return None
    return body_digest(body) != head.digest


def state(text: str | None, doc: str, version: str, fmt: int | None = None) -> str:
    """How a file on disk compares with a document ddflow is about to write over it: one of
    ``absent``, ``not-ours`` (no header), ``newer`` (written at a higher format level, of
    any document: rewriting it would lose what that ddflow wrote), ``edited`` (the body no
    longer matches its digest), ``other-doc`` (intact, but generated as another kind), ``older`` (written by an older release or format level) and
    ``current``. A version alone never makes a file ``newer`` (docs/ddflow/compatibility.md)."""
    fmt = FORMAT_LEVEL if fmt is None else fmt
    if text is None:
        return "absent"
    head, body = split(text)
    if head is None:
        return "not-ours"
    if newer(head, fmt):
        return "newer"
    if body_digest(body) != head.digest:
        return "edited"
    if head.doc != doc:
        return "other-doc"
    return "older" if head.fmt < fmt or is_older(head.version, version) else "current"


def truncate(body: str, max_bytes: int) -> str:
    """Cut ``body`` to at most ``max_bytes`` UTF-8 bytes, on a line boundary, and say so.

    The footer is explicit -- ``[truncated: N more; use --since/--limit]`` -- so a
    reader (or an agent) never mistakes a cut document for a complete one. ``max_bytes``
    of 0 or less means no cap. The footer is inside the budget; a cap smaller than the footer
    itself (about 41 bytes) yields the footer alone -- `registry.render_document` refuses such
    caps (exit 3) instead. When even the first line
    does not fit, it is cut mid-line and the count includes it as not (fully) shown.
    """
    body = normalize(body)
    if max_bytes <= 0 or len(body.encode("utf-8")) <= max_bytes:
        return body
    lines = body.splitlines(keepends=True)

    def footer(n: int) -> str:
        return f"[truncated: {n} more; use --since/--limit]\n"

    def size(text: str) -> int:
        return len(text.encode("utf-8"))

    # The largest prefix whose size PLUS its own footer fits the cap. The footer counts
    # for every prefix, the empty one included, so the result never exceeds max_bytes
    # (unless the footer alone does, which no sane cap allows). A shown part never ends
    # on blank lines; dropping them grows the footer's count, so the fit is re-checked.
    n, used, best = len(lines), 0, 0
    for k, line in enumerate(lines, 1):
        used += size(line)
        if used + size(footer(n - k)) <= max_bytes:
            best = k
    shown = lines[:best]
    while True:
        while shown and not shown[-1].strip():
            shown.pop()
        if not shown or size("".join(shown)) + size(footer(n - len(shown))) <= max_bytes:
            break
        shown.pop()
    if not shown:  # not even one whole line fits: cut the first on a character boundary
        room = max_bytes - size(footer(n)) - 1
        if room <= 0:  # the footer alone fills the cap: say so, add nothing else
            return footer(n)
        cut = lines[0].encode("utf-8")[:room].decode("utf-8", "ignore")
        return cut.rstrip("\n") + "\n" + footer(n)  # the cut line counts as not shown
    return "".join(shown) + footer(n - len(shown))


def one_line(s: str, limit: int = 140) -> str:
    """Collapse whitespace to single spaces and shorten at a word boundary with `` ...``.
    The shared helper for kinds that put free text on one list line."""
    s = " ".join((s or "").split())
    return s if len(s) <= limit else s[:limit].rsplit(" ", 1)[0] + " ..."
