"""The frame around a generated document: header, body digest, size cap, truncation.

A generated file is ``header + blank line + body``::

    <!-- ddflow:generated doc=roadmap v=0.1.9 body-sha256=0123456789ab -->
    Generated by ddflow from the event log - edit the source, not this file

    <body>

The digest covers the BODY text only (everything after the first blank line), never the
log: a log digest is stale the moment any event lands, while a body digest says exactly
one thing -- "has anyone edited this file since ddflow wrote it?". That is the hand-edit
test the writer (B-export-write) and ``--check`` rely on. Optional extra header attributes
(``last=<event id>`` for append-only documents) are written sorted, after the digest.

Nothing here reads the clock: the same body yields the same bytes.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field

#: Second header line. Fixed text.
NOTICE = "Generated by ddflow from the event log - edit the source, not this file"

#: stdout cap. ``--max-bytes`` overrides; 0 means no cap (what a file write uses).
DEFAULT_MAX_BYTES = 60_000

DIGEST_LEN = 12

_HEADER_RE = re.compile(
    r"^<!-- ddflow:generated doc=(?P<doc>[A-Za-z0-9_.-]+) v=(?P<v>\S+) "
    rf"body-sha256=(?P<sha>[0-9a-f]{{{DIGEST_LEN}}})(?P<extra>(?: [A-Za-z0-9_-]+=\S+)*) -->$"
)


@dataclass(frozen=True)
class Header:
    doc: str
    version: str
    digest: str
    extra: dict[str, str] = field(default_factory=dict)

    def line(self) -> str:
        extra = "".join(f" {k}={v}" for k, v in sorted(self.extra.items()))
        return (
            f"<!-- ddflow:generated doc={self.doc} v={self.version} "
            f"body-sha256={self.digest}{extra} -->"
        )


def body_digest(body: str) -> str:
    """The first ``DIGEST_LEN`` hex chars of sha256 over the body's UTF-8 bytes."""
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:DIGEST_LEN]


def normalize(body: str) -> str:
    """Exactly one trailing newline. Applied before digesting so a template's trailing
    blank lines cannot make two equal documents differ."""
    return body.rstrip("\n") + "\n"


def frame(body: str, doc: str, version: str, extra: dict[str, str] | None = None) -> str:
    """Header + notice + blank line + normalized body. Deterministic."""
    body = normalize(body)
    head = Header(doc, version, body_digest(body), dict(extra or {}))
    return f"{head.line()}\n{NOTICE}\n\n{body}"


def split(text: str) -> tuple[Header | None, str]:
    """``(header, body)`` of a generated file; ``(None, text)`` if it carries no header.

    The body is what follows the notice line and one blank line, byte for byte.
    """
    first, _, rest = text.partition("\n")
    m = _HEADER_RE.match(first)
    if not m:
        return None, text
    notice, _, after = rest.partition("\n")
    if notice != NOTICE or not after.startswith("\n"):
        return None, text
    extra = {}
    for pair in m.group("extra").split():
        k, _, v = pair.partition("=")
        extra[k] = v
    return Header(m.group("doc"), m.group("v"), m.group("sha"), extra), after[1:]


def hand_edited(text: str) -> bool | None:
    """True if a generated file's body no longer matches its header digest, False if it
    does, None if the text has no ddflow header (an unmarked file is not ours)."""
    head, body = split(text)
    if head is None:
        return None
    return body_digest(body) != head.digest


def truncate(body: str, max_bytes: int) -> str:
    """Cut ``body`` to at most ``max_bytes`` UTF-8 bytes, on a line boundary, and say so.

    The footer is explicit -- ``[truncated: N more lines; use --since/--limit]`` -- so a
    reader (or an agent) never mistakes a cut document for a complete one. ``max_bytes``
    of 0 or less means no cap. The footer is inside the budget, and at least one line is
    kept whenever any fits.
    """
    body = normalize(body)
    if max_bytes <= 0 or len(body.encode("utf-8")) <= max_bytes:
        return body
    lines = body.splitlines(keepends=True)

    def footer(n: int) -> str:
        return f"[truncated: {n} more lines; use --since/--limit]\n"

    kept: list[str] = []
    used = 0
    for i, line in enumerate(lines):
        ln = line
        size = len(ln.encode("utf-8"))
        if used + size + len(footer(len(lines) - i - 1).encode("utf-8")) > max_bytes and kept:
            break
        if used + size > max_bytes:  # a single over-long first line: hard cut, on a char edge
            cut = ln.encode("utf-8")[: max(max_bytes - 80, 0)]
            ln = cut.decode("utf-8", "ignore") + "\n"
            size = len(ln.encode("utf-8"))
        kept.append(ln)
        used += size
    while len(kept) > 1 and not kept[-1].strip():
        kept.pop()  # never end the shown part on blank lines
    more = len(lines) - len(kept)
    return "".join(kept).rstrip("\n") + "\n" + footer(more)


def one_line(s: str, limit: int = 140) -> str:
    """Collapse whitespace to single spaces and shorten at a word boundary with `` ...``.
    The shared helper for kinds that put free text on one list line."""
    s = " ".join((s or "").split())
    return s if len(s) <= limit else s[:limit].rsplit(" ", 1)[0] + " ..."
