"""Admission: may this item (or these globs) start beside what is already going?

One place for the glob-overlap question that `item_blocker` (the plan's live-lease check),
`leases.glob_clash` (`claim` and `update --globs`), `schedule._offered_overlap` (two items
offered in one plan) and the waiter reservation each asked with their own copy of the same
loop: skip your own, skip a different release line, then `conflicts` against the shared
globs. The copies were identical by hand; this makes them identical by construction.

Pure: no I/O, no clock of its own (``now`` is passed in).
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Literal

from ..config import Config
from ..core.model import Item, Lease, State
from .flow import line_key
from .globs import match as glob_match
from .globs import overlap as globs_overlap


def shared_globs(cfg: Config) -> list[str]:
    """`[lease] shared_globs` and `append_only_globs`: paths many items may hold at once
    (D-shared-globs), plus every SELECTED export target (D-export (2)): a generated document
    is regenerated by whoever runs `ddflow export`, so no claim on it is needed. A `region`
    target is a hand-written file with a generated region; it is shared for the same reason."""
    lease = cfg.lease
    return [
        *lease.shared_globs,
        *lease.append_only_globs,
        *(p for _d, p, _m in cfg.export.targets()),
    ]


def is_shared(glob: str, shared: list[str]) -> bool:
    """Is ``glob`` (a claim's glob or a staged path) INSIDE one of the ``shared`` globs?

    Inside, not overlapping: `docs/**` merely overlaps a shared `docs/CHANGELOG.md` and
    still claims the rest of `docs/`, so it stays exclusive. Matched as git matches the
    `.gitattributes` line (`core.globs`), so "shared" and "merged with union" agree.
    """
    return any(glob_match(glob, s, bare_any_depth=True) for s in shared)


def conflicts(
    mine: list[str], theirs: list[str], shared: list[str] | None = None
) -> list[tuple[str, str]]:
    """Overlapping pairs between two glob lists; a glob inside ``shared`` overlaps nothing.

    Every parallel item edits a changelog; exclusive leases on it serialised them all
    or pushed agents to commit it unleased (B07878037ab).
    """
    shared = shared or []
    mine = [a for a in mine if not is_shared(a, shared)]
    theirs = [b for b in theirs if not is_shared(b, shared)]
    return [(a, b) for a in mine for b in theirs if globs_overlap(a, b)]


@dataclass(frozen=True)
class Clash:
    """The first other item ``globs`` would overlap, with the pair that does."""

    item: str
    pair: tuple[str, str]
    #: The overlapped item's live lease; ``None`` when it is merely offered or reserved.
    lease: Lease | None = None


def glob_conflict(
    state: State,
    cfg: Config,
    it: Item,
    globs: list[str],
    holder: str = "",
    *,
    against: Literal["live", "offered"] = "live",
    live: dict[str, Lease] | None = None,
    others: Iterable[Item] = (),
) -> Clash | None:
    """The first other item whose globs overlap ``globs``, or ``None`` when none does.

    ``against="live"``: the live leases ``live`` (item id -> lease), skipping ``it``'s own
    and any held by ``holder`` (one author cannot collide with itself).
    ``against="offered"``: the items ``others`` (offered in one plan, or the item a waiter
    is queued for).

    Items on different release lines are different branches: `src/x.py` on 2.x and on 3.x
    cannot collide, and refusing it would serialise every port behind its fix.
    ``shared_globs`` overlap nothing.
    """
    mine = line_key(state, it, cfg)
    shared = shared_globs(cfg)
    if against == "live":
        for other_id, lease in (live or {}).items():
            if other_id == it.id or lease.holder == holder:
                continue
            other = state.items.get(other_id)
            if other is not None and line_key(state, other, cfg) != mine:
                continue
            pairs = conflicts(globs, lease.globs, shared)
            if pairs:
                return Clash(other_id, pairs[0], lease)
        return None
    for other in others:
        if line_key(state, other, cfg) != mine:
            continue
        pairs = conflicts(globs, list(other.globs), shared)
        if pairs:
            return Clash(other.id, pairs[0])
    return None
