"""Export core (B-export-core): registry, single-pass index, framing, truncation."""

from __future__ import annotations

import time
import types
from pathlib import Path

import pytest

from ddflow import __version__
from ddflow.core.model import Item, State
from ddflow.infra.log import EventLog
from ddflow.services.export import (
    EXIT_REFUSED,
    EXIT_UNAVAILABLE,
    DocKind,
    ExportError,
    Filters,
    frame,
    query,
    registry,
)

TEMPLATE = """# Roadmap
{% for p in phases %}

## {{ p.id }} {{ p.title }}

{% for t in p.tasks %}
- {{ t.id }} {{ t.title }} ({{ t.state }})
{% endfor %}
{% endfor %}
"""


def _data(q: query.Query, f: Filters) -> dict:
    phases = [
        {
            "id": p.id,
            "title": frame.one_line(p.title),
            "tasks": [
                {"id": t.id, "title": frame.one_line(t.title), "state": t.state}
                for t in q.tasks_of(p.id)
            ][: f.limit or None],
        }
        for p in q.phases()
    ]
    return {"phases": phases}


@pytest.fixture
def toy():
    kind = registry.register(
        DocKind(
            name="toyroad",
            default_target="TOY.md",
            data=_data,
            filters=frozenset({"limit"}),
            title="toy",
        )
    )
    yield kind
    registry.unregister("toyroad")


@pytest.fixture
def builtin(tmp_path: Path) -> Path:
    d = tmp_path / "shipped"
    d.mkdir()
    (d / "toyroad.md.j2").write_text(TEMPLATE)
    return d


def _log(repo: Path, order: str = "forward") -> query.Query:
    log = EventLog(repo, "a1")
    evs = [
        ("phase.added", "P2", {"title": "Second phase", "priority": 20}),
        ("phase.added", "P1", {"title": "First phase", "priority": 10}),
        ("task.added", "T-b", {"title": "bee", "parent": "P1", "kind": "task"}),
        ("task.added", "T-a", {"title": "ay", "parent": "P1", "kind": "task"}),
        ("task.added", "T-c", {"title": "see", "parent": "P2", "kind": "task"}),
    ]
    for kind, sub, data in evs if order == "forward" else reversed(evs):
        log.append(kind, sub, data)
    return query.load(repo)


GOLDEN_BODY = """# Roadmap

## P1 First phase

- T-a ay (open)
- T-b bee (open)

## P2 Second phase

- T-c see (open)
"""


def test_golden_body(tmp_path, toy, builtin):
    q = _log(tmp_path)
    assert registry.render_body("toyroad", q, builtin=builtin) == GOLDEN_BODY


def test_golden_document_has_header_and_digest(tmp_path, toy, builtin):
    q = _log(tmp_path)
    doc = registry.render_document("toyroad", q, builtin=builtin)
    digest = frame.body_digest(GOLDEN_BODY)
    assert doc == (
        f"<!-- ddflow:generated doc=toyroad v={__version__} body-sha256={digest} -->\n"
        "Generated by ddflow from the event log - edit the source, not this file\n\n" + GOLDEN_BODY
    )
    head, body = frame.split(doc)
    assert head is not None and head.doc == "toyroad" and head.digest == digest
    assert body == GOLDEN_BODY and frame.hand_edited(doc) is False


def test_same_log_identical_bytes_twice_and_across_write_order(tmp_path, toy, builtin):
    a, b = tmp_path / "a", tmp_path / "b"
    a.mkdir()
    b.mkdir()
    qa = _log(a)
    docs = [registry.render_document("toyroad", qa, builtin=builtin) for _ in range(2)]
    assert docs[0] == docs[1]
    # Events appended in a different order: the sort keys and id tie-breaks decide.
    qb = _log(b, order="reversed")
    assert registry.render_body("toyroad", qb, builtin=builtin) == GOLDEN_BODY


def test_hand_edit_detected_and_unmarked_is_none(tmp_path, toy, builtin):
    doc = registry.render_document("toyroad", _log(tmp_path), builtin=builtin)
    assert frame.hand_edited(doc.replace("bee", "BEE")) is True
    assert frame.hand_edited("# plain file\n") is None


def test_header_extra_attrs_round_trip():
    text = frame.frame("x\n", "k", "1.0", {"last": "abc123", "a": "1"})
    head, body = frame.split(text)
    assert head is not None and head.extra == {"a": "1", "last": "abc123"} and body == "x\n"
    assert text.splitlines()[0].endswith(
        "body-sha256=" + frame.body_digest("x\n") + " a=1 last=abc123 -->"
    )


def test_truncation_footer_is_explicit(tmp_path, toy, builtin):
    q = _log(tmp_path)
    full = registry.render_body("toyroad", q, builtin=builtin)
    cut = frame.truncate(full, 60)
    assert cut.endswith("more; use --since/--limit]\n")
    assert "[truncated: " in cut
    n = int(cut.rsplit("[truncated: ", 1)[1].split(" ")[0])
    assert n == len(full.splitlines()) - (len(cut.splitlines()) - 1)
    assert not cut.splitlines()[-2].strip() == ""  # never ends the shown part on a blank
    assert len(cut.encode()) <= 60
    # A cut document is still self-consistent: the digest matches what is shown.
    doc = registry.render_document("toyroad", q, builtin=builtin, max_bytes=240)
    assert frame.hand_edited(doc) is False and "[truncated:" in doc
    # No cap, or a cap that fits: untouched.
    assert frame.truncate(full, 0) == full == frame.truncate(full, 10_000)


def test_default_cap_is_60000():
    assert frame.DEFAULT_MAX_BYTES == 60_000
    big = "".join(f"line {i}\n" for i in range(20_000))
    out = frame.truncate(big, frame.DEFAULT_MAX_BYTES)
    assert len(out.encode()) <= 60_000 and out.endswith("use --since/--limit]\n")


def test_unsupported_filter_refused(tmp_path, toy, builtin):
    q = _log(tmp_path)
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", q, Filters(since="2026-01-01"), builtin=builtin)
    assert e.value.code == EXIT_REFUSED and "since" in str(e.value)
    assert "ay" in registry.render_body("toyroad", q, Filters(limit=1), builtin=builtin)


def test_unknown_kind_refused():
    with pytest.raises(ExportError) as e:
        registry.get("nope")
    assert e.value.code == EXIT_REFUSED


def test_duplicate_registration_and_bad_mode(toy):
    with pytest.raises(ValueError):
        registry.register(DocKind("toyroad", "X.md", _data))
    with pytest.raises(ValueError):
        DocKind("zzz", "X.md", _data, update_mode="sideways")
    with pytest.raises(ValueError):
        DocKind("zzz", "X.md", _data, filters=frozenset({"bogus"}))


def test_template_resolution_order(tmp_path, toy, builtin):
    q = _log(tmp_path)
    assert registry.resolve_template("toyroad", tmp_path, builtin=builtin).source == "builtin"
    proj = tmp_path / ".ddflow" / "templates" / "export"
    proj.mkdir(parents=True)
    (proj / "toyroad.md.j2").write_text("PROJECT {{ phases|length }}\n")
    t = registry.resolve_template("toyroad", tmp_path, builtin=builtin)
    assert t.source == "project"
    assert registry.render_body("toyroad", q, repo=tmp_path, builtin=builtin) == "PROJECT 2\n"
    (tmp_path / "mine.j2").write_text("CONFIG\n")
    t = registry.resolve_template("toyroad", tmp_path, {"toyroad": "mine.j2"}, builtin)
    assert t.source == "config"
    with pytest.raises(ExportError):  # a configured path that is missing is an error
        registry.resolve_template("toyroad", tmp_path, {"toyroad": "gone.j2"}, builtin)


def test_undefined_template_variable_is_an_error_not_empty(tmp_path, toy, builtin):
    (builtin / "toyroad.md.j2").write_text("{{ nope }}\n")
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", _log(tmp_path), builtin=builtin)
    assert e.value.code == EXIT_UNAVAILABLE


def test_missing_or_unreadable_log_is_could_not_run(tmp_path):
    with pytest.raises(ExportError) as e:
        query.load(tmp_path)
    assert e.value.code == EXIT_UNAVAILABLE


def test_index_5632_items_under_100ms():
    st = State()
    n_phases, per = 32, 175  # 32 phases + 5,600 tasks = 5,632 items
    for p in range(n_phases):
        st.items[f"P{p:02d}"] = Item(id=f"P{p:02d}", kind="phase", priority=p)
        for t in range(per):
            tid = f"P{p:02d}-T{t:03d}"
            st.items[tid] = Item(id=tid, kind="task", parent=f"P{p:02d}", priority=t % 7)
    assert len(st.items) == 5632
    elapsed = 9.9
    for _ in range(3):  # best of three: a loaded runner must not turn a pass into a flake
        start = time.perf_counter()
        q = query.Query(st, [])
        total = sum(len(q.tasks_of(p.id)) for p in q.phases())
        under = sum(len(q.tasks_under(p.id)) for p in q.phases())
        elapsed = min(elapsed, time.perf_counter() - start)
    assert total == under == n_phases * per
    assert elapsed < 0.1, f"index + lookups took {elapsed:.3f}s"
    first = q.tasks_of("P00")
    assert [t.id for t in first] == sorted(
        first_ids := [t.id for t in first], key=lambda i: (st.items[i].priority, i)
    )
    assert first_ids


def test_tasks_under_includes_subtasks_and_skips_removed():
    st = State()
    st.items["P"] = Item(id="P", kind="phase")
    st.items["A"] = Item(id="A", kind="task", parent="P")
    st.items["A1"] = Item(id="A1", kind="task", parent="A")
    st.items["X"] = Item(id="X", kind="task", parent="P", removed=True)
    q = query.Query(st, [])
    assert [t.id for t in q.tasks_under("P")] == ["A", "A1"]
    assert [t.id for t in q.tasks_of("P")] == ["A"]


@pytest.mark.parametrize("cap", [1, 20, 47, 66, 80, 100, 150, 400])
def test_truncate_never_exceeds_the_cap(cap):
    """A short first line plus a long second one: the footer must be inside the budget
    even when the first line is the only one kept (found by roborev)."""
    body = "Short heading line\n" + "B" * 500 + "\n" + "tail\n" * 40
    out = frame.truncate(body, cap)
    footer_len = len("[truncated: 41 more; use --since/--limit]\n")
    if cap >= footer_len + 3:
        assert len(out.encode()) <= cap, (cap, out)
    assert "[truncated: " in out
    assert frame.truncate("Short heading line\n" + "B" * 500 + "\n", 20).endswith("--limit]\n")


def test_document_cap_bounds_the_whole_framed_file(tmp_path, toy, builtin):
    q = _log(tmp_path)
    for cap in (240, 260, 400):
        doc = registry.render_document("toyroad", q, builtin=builtin, max_bytes=cap)
        assert len(doc.encode()) <= cap, (cap, len(doc.encode()))
        assert frame.hand_edited(doc) is False


def test_truncate_single_overlong_line_does_not_claim_nothing_is_missing():
    out = frame.truncate("x" * 200, 100)
    assert len(out.encode()) <= 100 and "[truncated: 1 more;" in out


def test_discover_failure_is_not_remembered(monkeypatch):
    calls = []

    def fake_import(name):
        if name.endswith("kind_bad"):
            calls.append(name)
            raise RuntimeError("bad kind module")
        return types.SimpleNamespace(__path__=["x"])

    monkeypatch.setattr(registry, "_discovered", [False])
    monkeypatch.setattr(registry.importlib, "import_module", fake_import)
    monkeypatch.setattr(
        registry.pkgutil, "iter_modules", lambda p: [types.SimpleNamespace(name="kind_bad")]
    )
    for _ in range(2):  # the second call must fail again, not return a partial registry
        with pytest.raises(RuntimeError):
            registry.names()
    assert len(calls) == 2


def test_unreadable_template_is_an_export_error(tmp_path, toy, builtin):
    (builtin / "toyroad.md.j2").write_bytes(b"\xff\xfe not utf-8")
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", _log(tmp_path), builtin=builtin)
    assert e.value.code == EXIT_UNAVAILABLE


@pytest.mark.parametrize("lines", [9, 10, 11, 99, 100, 101])
def test_truncate_exact_at_digit_boundaries(lines):
    body = "A" * 300 + "\n" + "b\n" * lines
    for cap in (100, 120):
        assert len(frame.truncate(body, cap).encode()) <= cap


def test_cap_below_the_frame_overhead_is_refused(tmp_path, toy, builtin):
    q = _log(tmp_path)
    for cap in (1, 100, 145):  # all smaller than the document itself
        with pytest.raises(ExportError) as e:
            registry.render_document("toyroad", q, builtin=builtin, max_bytes=cap)
        assert e.value.code == EXIT_REFUSED


def test_digest_is_12_lowercase_hex_of_sha256():
    import hashlib

    assert frame.body_digest("x\n") == hashlib.sha256(b"x\n").hexdigest()[:12]
    d = frame.body_digest("anything")
    assert len(d) == 12 and set(d) <= set("0123456789abcdef")
    # a known vector, so a different hash or width cannot pass by being self-consistent
    assert frame.body_digest("abc") == "ba7816bf8f01"


def test_log_of_only_unreadable_lines_is_could_not_run(tmp_path):
    ev = tmp_path / ".ddflow" / "events"
    ev.mkdir(parents=True)
    (ev / "a1.jsonl").write_text('{"ts": "2024-05-0')
    with pytest.raises(ExportError) as e:
        query.load(tmp_path)
    assert e.value.code == EXIT_UNAVAILABLE


def test_since_compares_instants_not_strings():
    from ddflow.core.events import Event

    def ev(ts):
        return Event(kind="note", subject="x", ts=ts, lamport=1, agent="a")

    q = query.Query(
        State(),
        [
            ev("2024-05-01T12:00:00+00:00"),  # exactly the cutoff
            ev("2024-05-01T10:00:00+02:00"),  # 08:00Z, before it
            ev("2024-05-02T00:00:00+00:00"),
        ],
    )
    got = [e.ts for e in q.events_of(since="2024-05-01T12:00:00Z")]
    assert got == ["2024-05-01T12:00:00+00:00", "2024-05-02T00:00:00+00:00"]
    assert len(q.events_of(since="2024-05-02")) == 1  # a bare date is a calendar day
    for bad in ("last tuesday", "garbage", "2024-13-99", "nope!!", "2024-5-1"):
        with pytest.raises(ExportError) as e:
            q.events_of(since=bad)
        assert e.value.code == EXIT_REFUSED, bad
    assert len(q.events_of(since="2024-05")) == 3 and len(q.events_of(since="2025")) == 0


def test_small_cap_that_the_document_fits_in_is_not_refused(tmp_path, toy, builtin):
    (builtin / "toyroad.md.j2").write_text("tiny\n")
    q = _log(tmp_path)
    full = registry.render_document("toyroad", q, builtin=builtin, max_bytes=0)
    assert len(full.encode()) < 200
    assert registry.render_document("toyroad", q, builtin=builtin, max_bytes=200) == full


# -- D-export-templates: sandboxed, user-overridable formatting ---------------------------


def _override(repo: Path, text: str) -> None:
    d = repo / ".ddflow" / "templates" / "export"
    d.mkdir(parents=True, exist_ok=True)
    (d / "toyroad.md.j2").write_text(text)


def test_project_override_changes_output_deterministically(tmp_path, toy, builtin):
    q = _log(tmp_path)
    base = registry.render_document("toyroad", q, repo=tmp_path, builtin=builtin)
    _override(tmp_path, "{% for p in phases %}{{ p.id }}={{ p.tasks|length }};{% endfor %}\n")
    a = registry.render_document("toyroad", q, repo=tmp_path, builtin=builtin)
    b = registry.render_document("toyroad", q, repo=tmp_path, builtin=builtin)
    assert a == b != base
    assert frame.split(a)[1] == "P1=2;P2=1;\n"
    # the header is added around the output; a template cannot remove or fake it
    assert frame.split(a)[0] is not None and frame.hand_edited(a) is False


def test_template_cannot_forge_or_drop_the_header(tmp_path, toy, builtin):
    _override(tmp_path, "<!-- ddflow:generated doc=x v=1 body-sha256=000000000000 -->\nhi\n")
    doc = registry.render_document("toyroad", _log(tmp_path), repo=tmp_path, builtin=builtin)
    head, body = frame.split(doc)
    assert head is not None and head.doc == "toyroad" and frame.hand_edited(doc) is False
    assert body.startswith("<!-- ddflow:generated")  # just body text, framed once more


ESCAPES = [
    "{{ ''.__class__.__mro__[1].__subclasses__() }}",
    "{{ phases.__class__ }}",
    "{{ (phases|first).__init__.__globals__ }}",
    "{{ self.__init__.__globals__ }}",
    "{{ cycler.__init__.__globals__ }}",
    "{{ lipsum.__globals__ }}",
    "{{ ''.join.__self__.__class__ }}",
    "{{ config }}",
    "{% for c in ().__class__.__base__.__subclasses__() %}{{ c }}{% endfor %}",
    "{{ namespace.__init__.__globals__['os'].popen('id').read() }}",
    "{{ [].__class__.__base__.__subclasses__()[0].__subclasshook__ }}",
    "{{ ''.format.__globals__ }}",
    "{{ request }}",
]


@pytest.mark.parametrize("src", ESCAPES)
def test_sandbox_refuses_escapes(tmp_path, toy, builtin, src):
    _override(tmp_path, src + "\n")
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", _log(tmp_path), repo=tmp_path, builtin=builtin)
    assert e.value.code == EXIT_UNAVAILABLE


def test_sandbox_blocks_open_and_import(tmp_path, toy, builtin):
    for src in ("{{ open('/etc/passwd').read() }}", "{{ __import__('os').getcwd() }}"):
        _override(tmp_path, src)
        with pytest.raises(ExportError) as e:
            registry.render_body("toyroad", _log(tmp_path), repo=tmp_path, builtin=builtin)
        assert e.value.code == EXIT_UNAVAILABLE


def test_template_errors_exit_2_and_write_nothing(tmp_path, toy, builtin):
    q = _log(tmp_path)
    out = tmp_path / "TOY.md"
    for src, needle in (
        ("{% for p in phases %}\n{{ p.id }}\n", "toyroad.md.j2:"),  # syntax: unclosed for
        ("ok\n{{ nope }}\n", "nope"),  # undefined variable
        ("{{ phases[0].nothing }}\n", "nothing"),
    ):
        _override(tmp_path, src)
        with pytest.raises(ExportError) as e:
            registry.render_document("toyroad", q, repo=tmp_path, builtin=builtin)
        assert e.value.code == EXIT_UNAVAILABLE and needle in str(e.value), (src, str(e.value))
    assert not out.exists()


def test_error_names_file_and_line(tmp_path, toy, builtin):
    _override(tmp_path, "line one\nline two\n{% if %}\n")
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", _log(tmp_path), repo=tmp_path, builtin=builtin)
    assert "toyroad.md.j2:3" in str(e.value)


def test_runaway_template_times_out_as_an_error():
    loop = "{% for i in range(90000) %}{% for j in range(90000) %}{% endfor %}{% endfor %}"
    start = time.perf_counter()
    with pytest.raises(ExportError) as e:
        registry.render(loop, {}, timeout_s=0.5)
    assert time.perf_counter() - start < 5 and "longer than" in str(e.value)


def test_template_receives_only_plain_data():
    class Model:
        title = "x"

    with pytest.raises(ExportError) as e:
        registry.render("{{ item.title }}", {"item": Model()})
    assert "item" in str(e.value) and "plain data" in str(e.value)
    assert registry.render("{{ a.b[1] }}", {"a": {"b": (1, 2)}}) == "2\n"  # tuples become lists
    with pytest.raises(ExportError):
        registry.render("x", {"k": {1: "non-string key"}})


def test_schema_version_is_exposed_to_templates(tmp_path, builtin):
    kind = DocKind("toyver", "T.md", lambda q, f: {}, schema_version=3)
    registry.register(kind)
    try:
        assert (
            registry.render("v{{ schema_version }}", {}, schema_version=kind.schema_version)
            == "v3\n"
        )
        (builtin / "toyver.md.j2").write_text("v{{ schema_version }}\n")
        assert registry.render_body("toyver", _log(tmp_path), builtin=builtin) == "v3\n"
    finally:
        registry.unregister("toyver")


def test_filters():
    r = registry.render
    assert r("{{ 'a *b* _c_ [d]'|md_escape }}", {}) == "a \\*b\\* \\_c\\_ \\[d\\]\n"
    assert r("{{ 'one  two\nthree four five'|wrap(9) }}", {}) == "one two\nthree\nfour five\n"
    assert r("{{ '2026-10-02T11:12:13+00:00'|date }}", {}) == "2026-10-02\n"
    assert r("{{ 'aaa bbb ccc ddd'|truncate(8) }}", {}) == "aaa bbb ...\n"
    assert r("{{ 3|bar(6, 10) }}", {}) == "[#####.....]\n"
    assert r("{{ 0|bar(0, 4) }}", {}) == "[....]\n"
    assert r("{{ 9|bar(3, 4) }}", {}) == "[####]\n"  # never overfills


def test_shipped_digest_tracks_the_shipped_template_only(tmp_path, toy, builtin):
    d1 = registry.shipped_digest("toyroad", builtin)
    assert d1 == registry.template_digest(TEMPLATE) and len(d1) == 12
    _override(tmp_path, "override\n")  # an override never changes the shipped digest
    assert registry.shipped_digest("toyroad", builtin) == d1
    (builtin / "toyroad.md.j2").write_text(TEMPLATE + "<!-- v2 -->\n")
    assert registry.shipped_digest("toyroad", builtin) != d1


def test_ad_hoc_template_renders_once(tmp_path, toy, builtin):
    q = _log(tmp_path)
    got = registry.render_body("toyroad", q, builtin=builtin, template="{{ phases|length }} phases")
    assert got == "2 phases\n"


def test_deadline_also_holds_off_the_main_thread():
    import threading

    box = {}

    def go():
        try:
            registry.render(
                "{% for i in range(90000) %}{% for j in range(90000) %}{% endfor %}{% endfor %}",
                {},
                timeout_s=0.3,
            )
        except ExportError as exc:
            box["err"] = exc

    t = threading.Thread(target=go)
    t.start()
    t.join(10)
    assert not t.is_alive() and "longer than" in str(box["err"])


def test_deadline_leaves_the_process_timer_alone():
    import signal

    seen = []
    old = signal.signal(signal.SIGALRM, lambda *a: seen.append(1))
    signal.setitimer(signal.ITIMER_REAL, 30)
    try:
        registry.render("x", {}, timeout_s=1)
        assert signal.getitimer(signal.ITIMER_REAL)[0] > 20  # the caller's timer survived
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, old)


def test_non_mapping_data_is_an_export_error_and_bar_never_underflows():
    for bad in (5, ["a"], "x"):
        with pytest.raises(ExportError):
            registry.render("{{ a }}", bad)
    assert registry.render("{{ -1|bar(4, 10) }}", {}) == "[..........]\n"


def test_truncate_cap_equal_to_the_footer_adds_no_separator():
    out = frame.truncate("x" * 100 + "\n", 41)
    assert out == "[truncated: 1 more; use --since/--limit]\n" and len(out.encode()) == 41


def test_unrepresentable_header_attribute_is_refused_not_written():
    for bad in ({"title": "Q4 Plan"}, {"t": ""}, {"a.b": "x"}):
        with pytest.raises(ValueError):
            frame.frame("x\n", "k", "1", bad)


def test_since_date_form_ignores_events_with_no_readable_date():
    from ddflow.core.events import Event

    def ev(ts):
        return Event(kind="note", subject="x", ts=ts, lamport=1, agent="a")

    q = query.Query(State(), [ev("unknown"), ev("2026-10-05-broken"), ev("2026-10-05T00:00:00Z")])
    assert [e.ts for e in q.events_of(since="2026-10-01")] == [
        "2026-10-05-broken",
        "2026-10-05T00:00:00Z",
    ]


def test_self_referential_data_is_an_export_error():
    d: dict = {}
    d["self"] = d
    with pytest.raises(ExportError):
        registry.render("x", d)


@pytest.mark.parametrize(
    "src", ["{{ [].pop() }}", "{{ {}.popitem() }}", "{{ 1 // 0 }}", "{{ 'a'.nope() }}"]
)
def test_any_exception_from_template_code_is_an_export_error(src):
    with pytest.raises(ExportError) as e:
        registry.render(src, {})
    assert e.value.code == EXIT_UNAVAILABLE


def test_bad_header_extra_through_render_document_is_refused(tmp_path, toy, builtin):
    with pytest.raises(ExportError) as e:
        registry.render_document(
            "toyroad", _log(tmp_path), builtin=builtin, extra={"title": "two words"}
        )
    assert e.value.code == EXIT_REFUSED
