"""`hooks status` sees ddflow's checks when the pre-commit framework is what arms them.

Bug B259fd32dbd: a repository whose `.git/hooks/pre-commit` and `commit-msg` are
generated by the pre-commit framework, and whose `.pre-commit-config.yaml` declares
local hooks running `ddflow hooks check-commit` / `hooks check-msg`, has both checks
armed -- a trailer-less message is refused. `hooks status` said "NOT installed ...
NOTHING checks it" and exited 2, because it only looked for ddflow's own marker in the
hook file, which a framework-generated hook never carries.

The fixtures below use the hook file pre-commit 4.6.1 writes, verbatim apart from the
interpreter path, because the detection keys on its header and its ARGS line.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from conftest import run_cli

from ddflow.services import enforce as E

_GENERATED = """#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/usr/bin/python3
ARGS=(hook-impl --config={config} --hook-type={hook_type})
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${{ARGS[@]}}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${{ARGS[@]}}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
"""

#: The shape of run_nemo_run's config: comments, a folded `>-` entry, a `language:
#: fail` hook, a check-commit hook with NO `stages` (so it runs at every stage) and a
#: check-msg hook confined to `commit-msg`.
_DDFLOW_CONFIG = """\
# a leading comment
default_install_hook_types: [pre-commit, commit-msg, post-commit]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: frozen-workflow-files
        name: workflow files frozen
        entry: >-
          these files are frozen history since the cutover (CLAUDE.md
          §Work queue) -- record it through ddflow instead
        language: fail
        files: ^(docs/todo\\.md|docs/log/)

      # the ddflow checks
      - id: ddflow-check-commit
        name: ddflow lease covers the staged paths
        entry: scripts/ddflow_hook.sh hooks check-commit
        language: system
        always_run: true
        pass_filenames: false

      - id: ddflow-check-msg
        name: "ddflow item trailer (Phase / Phase-ships)"
        entry: scripts/ddflow_hook.sh hooks check-msg
        language: system
        stages: [commit-msg]
        always_run: true
"""

_NO_DDFLOW_CONFIG = """\
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
      - id: msg-lint
        name: message lint
        entry: scripts/lint_msg.sh
        language: system
        stages: [commit-msg]
"""


def _framework(repo: Path, config: str, *, hook_types=("pre-commit", "commit-msg")) -> Path:
    """What `pre-commit install` leaves behind: the config, and one generated hook per type."""
    (repo / ".pre-commit-config.yaml").write_text(config, "utf-8")
    hooks = E.hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    for t in hook_types:
        h = hooks / t
        h.write_text(_GENERATED.format(config=".pre-commit-config.yaml", hook_type=t), "utf-8")
        h.chmod(0o755)
    return hooks


def _trailer_policy(repo: Path) -> None:
    run_cli(repo, "init")
    (repo / ".ddflow" / "config.toml").write_text(
        '[enforce]\ncommit_without_lease = "warn"\nrequire_item_trailer = true\n', "utf-8"
    )


# -- the regression: status over run_nemo_run's arrangement ------------------------------


def test_checks_armed_through_pre_commit_are_reported_installed(repo):
    _trailer_policy(repo)
    _framework(repo, _DDFLOW_CONFIG)

    code, out, err = run_cli(repo, "hooks", "status")

    assert code == 0, f"status exit {code}; a repo whose checks are armed is healthy\n{out}{err}"
    assert "pre-commit hook: installed" in out, out
    assert "commit-msg hook: installed" in out, out
    assert "NOTHING checks it" not in out, out
    assert "through the pre-commit framework" in out, (
        "status must say HOW the check is armed, or an operator reading 'installed' looks "
        f"for ddflow's own hook file and does not find it\n{out}"
    )
    assert "ddflow-check-commit" in out and "ddflow-check-msg" in out, out


def test_a_framework_hook_with_no_ddflow_entry_is_still_not_installed(repo):
    _trailer_policy(repo)
    _framework(repo, _NO_DDFLOW_CONFIG)

    code, out, _ = run_cli(repo, "hooks", "status")

    assert code == 2, out
    assert "pre-commit hook: NOT installed" in out, out
    assert "commit-msg hook: NOT installed" in out, out
    assert "NOTHING checks it" in out, out
    # The remedy must fit a framework hook: `hooks install` refuses over it, and an
    # edit to the generated file is lost at the next `pre-commit install`.
    assert ".pre-commit-config.yaml" in out, out


# -- stage semantics ----------------------------------------------------------------------


def _armed(repo: Path, config: str, name: str) -> E.Armed:
    _framework(repo, config)
    return E.armed(repo, name)


_ONE_HOOK = """\
{top}
repos:
- repo: local
  hooks:
  - id: dd
    name: dd
    entry: ddflow hooks {check}
    language: system
{extra}
"""


@pytest.mark.parametrize(
    ("top", "check", "extra", "name", "want"),
    [
        # no stages, no default_stages: pre-commit's default is EVERY stage
        ("", "check-commit", "", "pre-commit", True),
        ("", "check-msg", "", "commit-msg", True),
        # the pre-3.2 stage name `commit` means `pre-commit`
        ("", "check-commit", "    stages: [commit]", "pre-commit", True),
        ("", "check-commit", "    stages: [pre-push]", "pre-commit", False),
        ("", "check-msg", "    stages: [pre-commit]", "commit-msg", False),
        # default_stages applies to a hook that names none, in either spelling
        ("default_stages: [commit]", "check-commit", "", "pre-commit", True),
        ("default_stages: [commit]", "check-msg", "", "commit-msg", False),
        ("default_stages:\n  - commit-msg", "check-msg", "", "commit-msg", True),
        # a hook's own stages win over default_stages
        ("default_stages: [pre-push]", "check-msg", "    stages: [commit-msg]", "commit-msg", True),
        # the wrong check at the right stage is not the check
        ("", "check-msg", "    stages: [pre-commit]", "pre-commit", False),
        # check-msg reads the message FILE pre-commit passes; without it, it checks nothing
        ("", "check-msg", "    pass_filenames: false", "commit-msg", False),
        # `language: fail` never runs its entry
        ("", "check-commit", "    language: fail", "pre-commit", False),
        ("", "check-commit", "    language: pygrep", "pre-commit", False),
        # a hook whose filters match no staged file is SKIPPED ("no files to check"); at
        # commit-msg the file is the message file, which `types: [python]` never matches
        ("", "check-commit", "    files: ^src/", "pre-commit", False),
        ("", "check-msg", "    types: [python]", "commit-msg", False),
        ("", "check-commit", "    exclude: .*", "pre-commit", False),
        ("files: ^src/", "check-msg", "", "commit-msg", False),
        # ... unless it runs regardless of files; YAML 1.1 spells true `yes` too
        ("", "check-commit", "    files: ^src/\n    always_run: yes", "pre-commit", True),
        ("files: ^src/", "check-msg", "    always_run: true", "commit-msg", True),
        # the defaults are no filter at all
        ("exclude: ^$", "check-commit", "    types: [file]\n    files: ''", "pre-commit", True),
    ],
)
def test_the_stage_decides(repo, top, check, extra, name, want):
    config = _ONE_HOOK.format(top=top, check=check, extra=extra)
    if "language: " in extra:
        config = config.replace("    language: system\n", "")
    a = _armed(repo, config, name)
    assert bool(a.via) is want, (config, a)


def test_the_command_may_be_split_between_entry_and_args(repo):
    config = """\
repos:
  - repo: local
    hooks:
      - {id: dd-msg, name: dd, entry: 'python3 -m ddflow', args: [hooks, check-msg], language: system, stages: [commit-msg]}
"""
    assert E.armed(repo, "commit-msg").via == ""
    assert _armed(repo, config, "commit-msg").via == "pre-commit"


def test_a_command_that_is_not_ddflow_is_not_the_check(repo):
    config = _ONE_HOOK.format(top="", check="check-commit", extra="").replace(
        "entry: ddflow hooks", "entry: echo hooks"
    )
    assert _armed(repo, config, "pre-commit").via == ""


def test_ddflow_own_hook_kept_as_legacy_counts(repo):
    """`pre-commit install` over ddflow's hook moves it to pre-commit.legacy and runs it."""
    hooks = _framework(repo, _NO_DDFLOW_CONFIG, hook_types=("pre-commit",))
    legacy = hooks / "pre-commit.legacy"
    legacy.write_text(f"#!/bin/sh\n{E.HOOK_MARKER}\nexit 0\n", "utf-8")
    legacy.chmod(0o755)
    assert E.installed(repo, "pre-commit")
    legacy.chmod(0o644)  # pre-commit runs a legacy hook only if it is executable
    assert not E.installed(repo, "pre-commit")


def test_a_config_the_reader_cannot_parse_is_not_installed_and_says_why(repo):
    a = _armed(repo, "repos: &r\n  - repo: local\n", "pre-commit")
    assert a.via == ""
    assert "could not read" in a.detail, a


@pytest.mark.parametrize(
    "config",
    [
        # RecursionError inside the reader, not a crash of `hooks status`
        pytest.param("repos: " + "[" * 3000 + "]" * 3000 + "\n", id="deep-nesting"),
        # two documents; PyYAML refuses them
        pytest.param("a: 1\n---\nrepos: []\n", id="two-documents"),
    ],
)
def test_input_the_reader_refuses_is_reported_not_raised(repo, config):
    a = _armed(repo, config, "pre-commit")
    assert a.via == "" and "could not read" in a.detail, a


def test_a_config_path_the_file_system_refuses_is_not_a_crash(repo):
    hooks = _framework(repo, _DDFLOW_CONFIG)
    (hooks / "pre-commit").write_text(
        _GENERATED.format(config="a\x00b", hook_type="pre-commit"), "utf-8"
    )
    a = E.armed(repo, "pre-commit")
    assert a.via == "" and "could not read" in a.detail, a


def test_a_missing_config_is_not_installed(repo):
    _framework(repo, _DDFLOW_CONFIG)
    (repo / ".pre-commit-config.yaml").unlink()
    a = E.armed(repo, "pre-commit")
    assert a.via == "" and a.framework, a


def test_the_generated_hook_names_its_config(repo):
    """`pre-commit install -c other.yaml` bakes that path into ARGS; read that file."""
    hooks = _framework(repo, _NO_DDFLOW_CONFIG)
    (repo / "ci").mkdir()
    (repo / "ci" / "pc.yaml").write_text(_DDFLOW_CONFIG, "utf-8")
    (hooks / "pre-commit").write_text(
        _GENERATED.format(config="ci/pc.yaml", hook_type="pre-commit"), "utf-8"
    )
    assert E.armed(repo, "pre-commit").via == "pre-commit"


def test_core_hooks_path_is_followed(repo):
    subprocess.run(["git", "-C", str(repo), "config", "core.hooksPath", "githooks"], check=True)
    _framework(repo, _DDFLOW_CONFIG)
    assert (repo / "githooks" / "commit-msg").exists()
    assert E.installed(repo, "commit-msg")


def test_ddflow_own_hook_is_still_installed(repo):
    E.install(repo)
    assert E.armed(repo, "pre-commit").via == "ddflow"
    assert E.armed(repo, "commit-msg").via == "ddflow"


# -- the reader itself ----------------------------------------------------------------------


def test_the_reader_parses_the_config_shapes_pre_commit_accepts():
    doc = E.read_precommit_yaml(_DDFLOW_CONFIG)
    hooks = doc["repos"][0]["hooks"]
    assert [h["id"] for h in hooks] == [
        "ruff-check",
        "frozen-workflow-files",
        "ddflow-check-commit",
        "ddflow-check-msg",
    ]
    assert hooks[1]["entry"].startswith("these files are frozen history since the cutover")
    assert "\n" not in hooks[1]["entry"], "a folded scalar folds"
    assert hooks[1]["files"] == r"^(docs/todo\.md|docs/log/)"
    assert hooks[3]["name"] == "ddflow item trailer (Phase / Phase-ships)"
    assert hooks[3]["stages"] == ["commit-msg"]
    assert doc["default_install_hook_types"] == ["pre-commit", "commit-msg", "post-commit"]


def test_the_reader_handles_compact_sequences_quotes_and_comments():
    doc = E.read_precommit_yaml(
        "repos:\n"
        "- repo: https://github.com/x/y  # remote\n"
        "  rev: 'v1.0'\n"
        "  hooks:\n"
        "  - id: it's-fine # a comment\n"
        '    entry: "a # not a comment"\n'
        "    args: ['--x=1', \"--y\"]\n"
        "    stages:\n"
        "      - commit\n"
        "    alias: echo 'a #b'\n"
    )
    repo = doc["repos"][0]
    assert repo["repo"] == "https://github.com/x/y"
    assert repo["rev"] == "v1.0"
    hook = repo["hooks"][0]
    assert hook["id"] == "it's-fine"
    assert hook["entry"] == "a # not a comment"
    assert hook["args"] == ["--x=1", "--y"]
    assert hook["stages"] == ["commit"]
    # Inside a PLAIN scalar a quote is an ordinary character and ` #` starts a comment,
    # which is how PyYAML (and so pre-commit) reads it.
    assert hook["alias"] == "echo 'a"
