"""Export core (B-export-core): registry, single-pass index, framing, truncation."""

from __future__ import annotations

import time
import types
from pathlib import Path

import pytest

from ddflow import __version__
from ddflow.core.model import Item, State
from ddflow.infra.log import EventLog
from ddflow.services.export import (
    EXIT_REFUSED,
    EXIT_UNAVAILABLE,
    DocKind,
    ExportError,
    Filters,
    frame,
    query,
    registry,
)

TEMPLATE = """# Roadmap
{% for p in phases %}

## {{ p.id }} {{ p.title }}

{% for t in p.tasks %}
- {{ t.id }} {{ t.title }} ({{ t.state }})
{% endfor %}
{% endfor %}
"""


def _data(q: query.Query, f: Filters) -> dict:
    phases = [
        {
            "id": p.id,
            "title": frame.one_line(p.title),
            "tasks": [
                {"id": t.id, "title": frame.one_line(t.title), "state": t.state}
                for t in q.tasks_of(p.id)
            ][: f.limit or None],
        }
        for p in q.phases()
    ]
    return {"phases": phases}


@pytest.fixture
def toy():
    kind = registry.register(
        DocKind(
            name="toyroad",
            default_target="TOY.md",
            data=_data,
            filters=frozenset({"limit"}),
            title="toy",
        )
    )
    yield kind
    registry.unregister("toyroad")


@pytest.fixture
def builtin(tmp_path: Path) -> Path:
    d = tmp_path / "shipped"
    d.mkdir()
    (d / "toyroad.md.j2").write_text(TEMPLATE)
    return d


def _log(repo: Path, order: str = "forward") -> query.Query:
    log = EventLog(repo, "a1")
    evs = [
        ("phase.added", "P2", {"title": "Second phase", "priority": 20}),
        ("phase.added", "P1", {"title": "First phase", "priority": 10}),
        ("task.added", "T-b", {"title": "bee", "parent": "P1", "kind": "task"}),
        ("task.added", "T-a", {"title": "ay", "parent": "P1", "kind": "task"}),
        ("task.added", "T-c", {"title": "see", "parent": "P2", "kind": "task"}),
    ]
    for kind, sub, data in evs if order == "forward" else reversed(evs):
        log.append(kind, sub, data)
    return query.load(repo)


GOLDEN_BODY = """# Roadmap

## P1 First phase

- T-a ay (open)
- T-b bee (open)

## P2 Second phase

- T-c see (open)
"""


def test_golden_body(tmp_path, toy, builtin):
    q = _log(tmp_path)
    assert registry.render_body("toyroad", q, builtin=builtin) == GOLDEN_BODY


def test_golden_document_has_header_and_digest(tmp_path, toy, builtin):
    q = _log(tmp_path)
    doc = registry.render_document("toyroad", q, builtin=builtin)
    digest = frame.body_digest(GOLDEN_BODY)
    assert doc == (
        f"<!-- ddflow:generated doc=toyroad v={__version__} body-sha256={digest} -->\n"
        "Generated by ddflow from the event log - edit the source, not this file\n\n" + GOLDEN_BODY
    )
    head, body = frame.split(doc)
    assert head is not None and head.doc == "toyroad" and head.digest == digest
    assert body == GOLDEN_BODY and frame.hand_edited(doc) is False


def test_same_log_identical_bytes_twice_and_across_write_order(tmp_path, toy, builtin):
    a, b = tmp_path / "a", tmp_path / "b"
    a.mkdir()
    b.mkdir()
    qa = _log(a)
    docs = [registry.render_document("toyroad", qa, builtin=builtin) for _ in range(2)]
    assert docs[0] == docs[1]
    # Events appended in a different order: the sort keys and id tie-breaks decide.
    qb = _log(b, order="reversed")
    assert registry.render_body("toyroad", qb, builtin=builtin) == GOLDEN_BODY


def test_hand_edit_detected_and_unmarked_is_none(tmp_path, toy, builtin):
    doc = registry.render_document("toyroad", _log(tmp_path), builtin=builtin)
    assert frame.hand_edited(doc.replace("bee", "BEE")) is True
    assert frame.hand_edited("# plain file\n") is None


def test_header_extra_attrs_round_trip():
    text = frame.frame("x\n", "k", "1.0", {"last": "abc123", "a": "1"})
    head, body = frame.split(text)
    assert head is not None and head.extra == {"a": "1", "last": "abc123"} and body == "x\n"
    assert text.splitlines()[0].endswith(
        "body-sha256=" + frame.body_digest("x\n") + " a=1 last=abc123 -->"
    )


def test_truncation_footer_is_explicit(tmp_path, toy, builtin):
    q = _log(tmp_path)
    full = registry.render_body("toyroad", q, builtin=builtin)
    cut = frame.truncate(full, 60)
    assert cut.endswith("more lines; use --since/--limit]\n")
    assert "[truncated: " in cut
    n = int(cut.rsplit("[truncated: ", 1)[1].split(" ")[0])
    assert n == len(full.splitlines()) - (len(cut.splitlines()) - 1)
    assert not cut.splitlines()[-2].strip() == ""  # never ends the shown part on a blank
    assert len(cut.encode()) <= 60
    # A cut document is still self-consistent: the digest matches what is shown.
    doc = registry.render_document("toyroad", q, builtin=builtin, max_bytes=240)
    assert frame.hand_edited(doc) is False and "[truncated:" in doc
    # No cap, or a cap that fits: untouched.
    assert frame.truncate(full, 0) == full == frame.truncate(full, 10_000)


def test_default_cap_is_60000():
    assert frame.DEFAULT_MAX_BYTES == 60_000
    big = "".join(f"line {i}\n" for i in range(20_000))
    out = frame.truncate(big, frame.DEFAULT_MAX_BYTES)
    assert len(out.encode()) <= 60_000 and out.endswith("use --since/--limit]\n")


def test_unsupported_filter_refused(tmp_path, toy, builtin):
    q = _log(tmp_path)
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", q, Filters(since="2026-01-01"), builtin=builtin)
    assert e.value.code == EXIT_REFUSED and "since" in str(e.value)
    assert "ay" in registry.render_body("toyroad", q, Filters(limit=1), builtin=builtin)


def test_unknown_kind_refused():
    with pytest.raises(ExportError) as e:
        registry.get("nope")
    assert e.value.code == EXIT_REFUSED


def test_duplicate_registration_and_bad_mode(toy):
    with pytest.raises(ValueError):
        registry.register(DocKind("toyroad", "X.md", _data))
    with pytest.raises(ValueError):
        DocKind("zzz", "X.md", _data, update_mode="sideways")
    with pytest.raises(ValueError):
        DocKind("zzz", "X.md", _data, filters=frozenset({"bogus"}))


def test_template_resolution_order(tmp_path, toy, builtin):
    q = _log(tmp_path)
    assert registry.resolve_template("toyroad", tmp_path, builtin=builtin).source == "builtin"
    proj = tmp_path / ".ddflow" / "templates" / "export"
    proj.mkdir(parents=True)
    (proj / "toyroad.md.j2").write_text("PROJECT {{ phases|length }}\n")
    t = registry.resolve_template("toyroad", tmp_path, builtin=builtin)
    assert t.source == "project"
    assert registry.render_body("toyroad", q, repo=tmp_path, builtin=builtin) == "PROJECT 2\n"
    (tmp_path / "mine.j2").write_text("CONFIG\n")
    t = registry.resolve_template("toyroad", tmp_path, {"toyroad": "mine.j2"}, builtin)
    assert t.source == "config"
    with pytest.raises(ExportError):  # a configured path that is missing is an error
        registry.resolve_template("toyroad", tmp_path, {"toyroad": "gone.j2"}, builtin)


def test_undefined_template_variable_is_an_error_not_empty(tmp_path, toy, builtin):
    (builtin / "toyroad.md.j2").write_text("{{ nope }}\n")
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", _log(tmp_path), builtin=builtin)
    assert e.value.code == EXIT_UNAVAILABLE


def test_missing_or_unreadable_log_is_could_not_run(tmp_path):
    with pytest.raises(ExportError) as e:
        query.load(tmp_path)
    assert e.value.code == EXIT_UNAVAILABLE


def test_index_5632_items_under_100ms():
    st = State()
    n_phases, per = 32, 175  # 32 phases + 5,600 tasks = 5,632 items
    for p in range(n_phases):
        st.items[f"P{p:02d}"] = Item(id=f"P{p:02d}", kind="phase", priority=p)
        for t in range(per):
            tid = f"P{p:02d}-T{t:03d}"
            st.items[tid] = Item(id=tid, kind="task", parent=f"P{p:02d}", priority=t % 7)
    assert len(st.items) == 5632
    elapsed = 9.9
    for _ in range(3):  # best of three: a loaded runner must not turn a pass into a flake
        start = time.perf_counter()
        q = query.Query(st, [])
        total = sum(len(q.tasks_of(p.id)) for p in q.phases())
        under = sum(len(q.tasks_under(p.id)) for p in q.phases())
        elapsed = min(elapsed, time.perf_counter() - start)
    assert total == under == n_phases * per
    assert elapsed < 0.1, f"index + lookups took {elapsed:.3f}s"
    first = q.tasks_of("P00")
    assert [t.id for t in first] == sorted(
        first_ids := [t.id for t in first], key=lambda i: (st.items[i].priority, i)
    )
    assert first_ids


def test_tasks_under_includes_subtasks_and_skips_removed():
    st = State()
    st.items["P"] = Item(id="P", kind="phase")
    st.items["A"] = Item(id="A", kind="task", parent="P")
    st.items["A1"] = Item(id="A1", kind="task", parent="A")
    st.items["X"] = Item(id="X", kind="task", parent="P", removed=True)
    q = query.Query(st, [])
    assert [t.id for t in q.tasks_under("P")] == ["A", "A1"]
    assert [t.id for t in q.tasks_of("P")] == ["A"]


@pytest.mark.parametrize("cap", [1, 20, 47, 66, 80, 100, 150, 400])
def test_truncate_never_exceeds_the_cap(cap):
    """A short first line plus a long second one: the footer must be inside the budget
    even when the first line is the only one kept (found by roborev)."""
    body = "Short heading line\n" + "B" * 500 + "\n" + "tail\n" * 40
    out = frame.truncate(body, cap)
    footer_len = len("[truncated: 41 more lines; use --since/--limit]\n")
    if cap >= footer_len + 3:
        assert len(out.encode()) <= cap, (cap, out)
    assert "[truncated: " in out
    assert frame.truncate("Short heading line\n" + "B" * 500 + "\n", 20).count("\n") >= 2


def test_document_cap_bounds_the_whole_framed_file(tmp_path, toy, builtin):
    q = _log(tmp_path)
    for cap in (240, 260, 400):
        doc = registry.render_document("toyroad", q, builtin=builtin, max_bytes=cap)
        assert len(doc.encode()) <= cap, (cap, len(doc.encode()))
        assert frame.hand_edited(doc) is False


def test_truncate_single_overlong_line_does_not_claim_nothing_is_missing():
    out = frame.truncate("x" * 200, 100)
    assert len(out.encode()) <= 100 and "[truncated: 1 more lines;" in out


def test_discover_failure_is_not_remembered(monkeypatch):
    calls = []

    def fake_import(name):
        if name.endswith("kind_bad"):
            calls.append(name)
            raise RuntimeError("bad kind module")
        return types.SimpleNamespace(__path__=["x"])

    monkeypatch.setattr(registry, "_discovered", [False])
    monkeypatch.setattr(registry.importlib, "import_module", fake_import)
    monkeypatch.setattr(
        registry.pkgutil, "iter_modules", lambda p: [types.SimpleNamespace(name="kind_bad")]
    )
    for _ in range(2):  # the second call must fail again, not return a partial registry
        with pytest.raises(RuntimeError):
            registry.names()
    assert len(calls) == 2


def test_unreadable_template_is_an_export_error(tmp_path, toy, builtin):
    (builtin / "toyroad.md.j2").write_bytes(b"\xff\xfe not utf-8")
    with pytest.raises(ExportError) as e:
        registry.render_body("toyroad", _log(tmp_path), builtin=builtin)
    assert e.value.code == EXIT_UNAVAILABLE


@pytest.mark.parametrize("lines", [9, 10, 11, 99, 100, 101])
def test_truncate_exact_at_digit_boundaries(lines):
    body = "A" * 300 + "\n" + "b\n" * lines
    for cap in (100, 120):
        assert len(frame.truncate(body, cap).encode()) <= cap


def test_cap_below_the_frame_overhead_is_refused(tmp_path, toy, builtin):
    q = _log(tmp_path)
    for cap in (1, 100, 145):
        with pytest.raises(ExportError) as e:
            registry.render_document("toyroad", q, builtin=builtin, max_bytes=cap)
        assert e.value.code == EXIT_REFUSED
