"""`hooks install` over a hook the pre-commit framework generated.

Bug B695d7925bf: refusing over an existing pre-commit hook, `hooks install` told the
operator to add ddflow's check line to `.git/hooks/pre-commit` -- on run_nemo_run a file
carrying "File generated by pre-commit", which the next `pre-commit install` rewrites,
silently dropping the edit. The check belongs in `.pre-commit-config.yaml` as a
`repo: local` hook; and where the config already has one, there is nothing to install.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from conftest import run_cli
from test_hooks_status_precommit import _DDFLOW_CONFIG, _NO_DDFLOW_CONFIG, _framework


def test_the_refusal_points_at_the_config_not_the_generated_file(repo):
    run_cli(repo, "init")
    hooks = _framework(repo, _NO_DDFLOW_CONFIG)
    before = (hooks / "pre-commit").read_text()

    code, out, err = run_cli(repo, "hooks", "install")
    text = out + err

    assert code != 0, text
    assert "Add this line to it yourself" not in text, text
    assert ".pre-commit-config.yaml" in text and "repo: local" in text, text
    assert "pre-commit install" in text, "say why the generated file is the wrong place"
    assert (hooks / "pre-commit").read_text() == before


def test_checks_the_framework_already_runs_are_not_refused(repo):
    run_cli(repo, "init")
    hooks = _framework(repo, _DDFLOW_CONFIG)
    before = {n: (hooks / n).read_text() for n in ("pre-commit", "commit-msg")}

    code, out, err = run_cli(repo, "hooks", "install")

    assert code == 0, out + err
    assert "REFUSED" not in out + err and "NOT INSTALLED" not in out + err, out + err
    assert "pre-commit framework" in out, out
    assert {n: (hooks / n).read_text() for n in before} == before, "generated hooks untouched"


_CHECK_COMMIT_ONLY = """\
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: local
    hooks:
      - id: ddflow-check-commit
        name: ddflow lease covers the staged paths
        entry: ddflow hooks check-commit
        language: system
        always_run: true
        pass_filenames: false
"""


def test_an_unarmed_commit_msg_is_reported_with_the_config_remedy(repo):
    """The lease check armed through the framework, the trailer check not: the same
    contract as ddflow's own pre-commit hook beside a foreign commit-msg one
    (test_commit_trailer: exit 0, NOT INSTALLED with what to add) -- the remedy being
    the config's, not a line in the generated file."""
    run_cli(repo, "init")
    _framework(repo, _CHECK_COMMIT_ONLY)

    code, out, err = run_cli(repo, "hooks", "install")

    assert code == 0, out + err
    assert "nothing to install" in out, out
    assert "NOT INSTALLED" in out and "hooks check-msg" in out, out
    assert "Add this line to it yourself" not in out and "repo: local" in out, out
