"""B-upgrade.1-stamp: the version stamp (`ddflow.seen`), skew detection and the skew guard.

Decisions D-upgrade-event-kinds and D-upgrade-skew-guard. Every test here builds a throwaway
project; the old-version case uses a log generated by a real ddflow 0.1.3
(tests/fixtures/upgrade/log-0.1.3.jsonl) rather than one this code wrote."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest
from conftest import run_cli

import ddflow
from ddflow.core import model as M
from ddflow.core.events import (
    OLDER_MARK,
    Event,
    SkewRefused,
    is_older,
    stamp_facts,
    version_key,
)
from ddflow.core.model import fold
from ddflow.infra.log import EventLog
from ddflow.services import install_info as II

FIXTURE = Path(__file__).parent / "fixtures" / "upgrade" / "log-0.1.3.jsonl"


def kinds(log: EventLog, kind: str) -> list[Event]:
    return [e for e in log.read_all() if e.kind == kind]


def stamp_newer(repo: Path, version: str = "99.0.0", agent: str = "future") -> None:
    """A log a NEWER ddflow has worked on: its stamp, in its own shard, as a merge brings it."""
    shard = repo / ".ddflow" / "events"
    shard.mkdir(parents=True, exist_ok=True)
    ev = Event(
        kind="ddflow.seen",
        subject="ddflow",
        data={"version": version, "install": "installed"},
        agent=agent,
        lamport=1,
        ts="2099-01-01T00:00:00.000000Z",
    )
    ev = Event(**{**ev.__dict__, "id": ev.compute_id()})
    with (shard / f"{agent}.jsonl").open("a") as fh:
        fh.write(ev.to_json() + "\n")


@pytest.fixture
def older_than_log(repo: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """The running ddflow is OLDER than the log's highest stamp."""
    stamp_newer(repo)
    return repo


# -- versions ----------------------------------------------------------------------------


def test_versions_compare_as_numbers_not_text():
    assert version_key("0.1.10") > version_key("0.1.9")
    assert is_older("0.1.9", "0.1.10")
    assert not is_older("0.1.10", "0.1.10")
    assert not is_older("unknown", "0.1.10")  # an unparsable version is never a reason to refuse
    assert not is_older("0.1.10", "")
    # Two spellings of one release are one release; a pre-release is older than its release.
    assert not is_older("0.2", "0.2.0") and not is_older("0.2.0", "0.2")
    assert is_older("0.2.0rc1", "0.2.0") and not is_older("0.2.0", "0.2.0rc1")
    assert is_older("0.2.0rc1", "0.2.0rc2") and is_older("0.1.10", "0.2.0rc1")
    assert is_older("0.2.0.dev3", "0.2.0a1") and is_older("0.2.0a5", "0.2.0b1")
    assert is_older("0.2.0b2", "0.2.0rc1") and not is_older("0.2.0rc1", "0.2.0.dev3")
    assert version_key("v0.2.0") == version_key("0.2.0") and version_key("dev") == ()


# -- the stamp ---------------------------------------------------------------------------


def test_first_write_stamps_the_version_once_per_agent_and_version(repo: Path):
    log = EventLog(repo, "a1")
    log.append("phase.added", "P1", {"title": "p"})
    log.append("phase.added", "P2", {"title": "p"})
    seen = kinds(log, "ddflow.seen")
    assert len(seen) == 1
    assert seen[0].data["version"] == ddflow.__version__
    assert seen[0].data["install"]
    # The stamp precedes the event that caused it.
    order = [e.kind for e in log.read_all()]
    assert order[:2] == ["ddflow.seen", "phase.added"]
    # A second agent stamps its own first write, and a new process of the same agent does not.
    EventLog(repo, "a2").append("phase.added", "P3", {"title": "p"})
    EventLog(repo, "a1").append("phase.added", "P4", {"title": "p"})
    assert sorted(e.agent for e in kinds(log, "ddflow.seen")) == ["a1", "a2"]


def test_a_new_version_stamps_again_and_the_fold_keeps_the_highest(
    repo: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.setattr(ddflow, "__version__", "0.1.9")
    log = EventLog(repo, "a1")
    log.append("phase.added", "P1", {"title": "p"})
    monkeypatch.setattr(ddflow, "__version__", "0.1.10")
    log.append("phase.added", "P2", {"title": "p"})
    # An older ddflow stamping after a newer one (policy off) does not lower the project's version.
    assert [e.data["version"] for e in kinds(log, "ddflow.seen")] == ["0.1.9", "0.1.10"]
    st = fold(log.read_all())
    assert st.highest_version == "0.1.10"
    assert set(st.ddflow_versions) == {"0.1.9", "0.1.10"}
    assert st.ddflow_versions["0.1.10"]["agents"] == ["a1"]


def test_stamp_writes_the_local_marker(repo: Path):
    EventLog(repo, "a1").append("phase.added", "P1", {"title": "p"})
    marker = json.loads((repo / ".ddflow" / "local" / "seen.json").read_text())
    assert marker["version"] == ddflow.__version__
    assert (repo / ".ddflow" / "local" / ".gitignore").read_text().strip() == "*"


def test_an_old_unstamped_log_reads_clean_and_is_stamped_on_first_write(repo: Path):
    events = repo / ".ddflow" / "events"
    events.mkdir(parents=True)
    shutil.copy(FIXTURE, events / "fx013.jsonl")
    log = EventLog(repo, "fx013")
    before = fold(log.read_all())  # strict: nothing in a 0.1.3 log is unknown to this code
    assert before.skipped_kinds == {} and before.highest_version == ""
    assert not log.verify()
    log.append("phase.added", "P2", {"title": "second"})
    after = fold(log.read_all())
    assert after.highest_version == ddflow.__version__
    assert {"P1", "P2"} <= set(after.items)


def test_a_fresh_project_is_stamped_by_ddflow_init_and_first_add(repo: Path):
    assert run_cli(repo, "init")[0] == 0
    assert run_cli(repo, "phase", "add", "P1", "--title", "p")[0] == 0
    st = fold(EventLog(repo).read_all())
    assert st.highest_version == ddflow.__version__


# -- what an older reader does with the new kinds ----------------------------------------


def test_an_older_reader_skips_the_new_kinds_with_a_count_not_an_error(
    repo: Path, monkeypatch: pytest.MonkeyPatch
):
    log = EventLog(repo, "a1")
    log.append("phase.added", "P1", {"title": "p"})
    events = log.read_all()
    assert any(e.kind == "ddflow.seen" for e in events)
    # A 0.1.3-like vocabulary: no stamp kinds.
    old = {
        k: v
        for k, v in M.HANDLERS.items()
        if k not in ("ddflow.seen", "skew.overridden", "upgrade.applied")
    }
    monkeypatch.setattr(M, "HANDLERS", old)
    st = fold(events, strict=False)
    assert st.skipped_kinds == {"ddflow.seen": 1}
    assert "P1" in st.items
    with pytest.raises(ValueError):
        fold(events, strict=True)


def test_an_event_with_a_newer_schema_is_counted_like_a_skipped_kind():
    e = Event(kind="phase.added", subject="P1", data={"title": "p"}, lamport=1, schema=99)
    st = fold([e], strict=False)
    assert st.items == {}
    assert st.skipped_kinds == {"phase.added (schema 99)": 1}


# -- the skew guard ----------------------------------------------------------------------


def test_facts_name_the_highest_stamp_and_who_wrote_it(older_than_log: Path):
    facts = stamp_facts(EventLog(older_than_log, "me").read_all(), "me", "0.1.10")
    assert (facts.highest, facts.highest_by, facts.seen_by_me) == ("99.0.0", "future", False)


def test_an_older_ddflow_is_refused_its_first_write_naming_the_version(older_than_log: Path):
    log = EventLog(older_than_log, "me")
    with pytest.raises(SkewRefused) as exc:
        log.append("phase.added", "P1", {"title": "p"})
    msg = str(exc.value)
    assert "upgrade ddflow-mcp to >= 99.0.0" in msg.lower().replace(
        "upgrade ddflow-mcp", "upgrade ddflow-mcp"
    )
    assert "--allow-older-version" in msg and "ask the user" in msg
    # Nothing was written, not even a stamp, and reads are untouched.
    assert not (older_than_log / ".ddflow" / "events" / "me.jsonl").exists()
    assert fold(log.read_all()).highest_version == "99.0.0"


def test_the_cli_refuses_a_write_with_exit_3_and_still_reads(older_than_log: Path):
    code, out, err = run_cli(older_than_log, "phase", "add", "P1", "--title", "p")
    assert code == 3, (out, err)
    assert "Upgrade ddflow-mcp to >= 99.0.0" in err
    assert run_cli(older_than_log, "status")[0] == 0
    assert run_cli(older_than_log, "history")[0] in (0, 2)


def test_an_override_is_recorded_session_scoped_and_marks_the_events(older_than_log: Path):
    log = EventLog(older_than_log, "me")
    assert log.override_skew("operator said go") is not None
    ov = kinds(log, "skew.overridden")
    assert len(ov) == 1
    assert ov[0].data["running"] == ddflow.__version__
    assert ov[0].data["log_version"] == "99.0.0"
    assert ov[0].data["reason"] == "operator said go"
    log.append("phase.added", "P1", {"title": "p"})
    log.append("phase.added", "P2", {"title": "p"})
    added = kinds(log, "phase.added")
    assert [e.data[OLDER_MARK] for e in added] == [ddflow.__version__] * 2
    st = fold(log.read_all())
    assert st.older_version_events[ddflow.__version__] >= 2
    assert st.skew_overrides[0]["reason"] == "operator said go"
    # Idempotent within the session: no second override event.
    log.override_skew("again")
    assert len(kinds(log, "skew.overridden")) == 1


def test_an_override_needs_a_reason(older_than_log: Path):
    with pytest.raises(SkewRefused):
        EventLog(older_than_log, "me").override_skew("  ")


def test_a_second_session_and_another_agent_are_refused_again(older_than_log: Path):
    # Session one: opened before the skew was found, then overridden.
    log = EventLog(older_than_log, "me")
    log.override_skew("go")
    log.append("session.started", "S1", {})
    log.override_skew("go")  # the open session is now S1: a new, scoped override
    log.append("phase.added", "P1", {"title": "p"})
    log.append("session.ended", "S1", {})
    # Session two is a new scope: refused until it is overridden itself.
    with pytest.raises(SkewRefused):
        log.append("phase.added", "P2", {"title": "p"})
    # Another agent never inherits it.
    with pytest.raises(SkewRefused):
        EventLog(older_than_log, "other").append("phase.added", "P3", {"title": "p"})


def test_a_newer_stamp_after_an_override_refuses_again(older_than_log: Path):
    log = EventLog(older_than_log, "me")
    log.override_skew("go")
    log.append("phase.added", "P1", {"title": "p"})
    stamp_newer(older_than_log, "100.0.0", agent="future2")
    with pytest.raises(SkewRefused):
        log.append("phase.added", "P2", {"title": "p"})


def test_no_skew_means_no_override_and_no_event(repo: Path):
    log = EventLog(repo, "me")
    log.append("phase.added", "P1", {"title": "p"})
    assert log.override_skew("not needed") is None
    assert kinds(log, "skew.overridden") == []


# -- surfaces: CLI, MCP, history, replay, doctor, config ---------------------------------


def test_the_cli_override_flag_records_it_and_lets_the_write_through(older_than_log: Path):
    code, out, err = run_cli(
        older_than_log,
        "phase",
        "add",
        "P1",
        "--title",
        "p",
        "--allow-older-version",
        "--reason",
        "operator said go",
        agent="me",
    )
    assert code == 0, (out, err)
    log = EventLog(older_than_log, "me")
    assert kinds(log, "skew.overridden")[0].data["reason"] == "operator said go"
    assert kinds(log, "phase.added")[0].data[OLDER_MARK] == ddflow.__version__
    # The next command of the same session needs no flag...
    assert run_cli(older_than_log, "phase", "add", "P2", "--title", "p", agent="me")[0] == 0
    # ...another agent still does.
    assert run_cli(older_than_log, "phase", "add", "P3", "--title", "p", agent="other")[0] == 3


def test_the_cli_override_flag_needs_a_reason(older_than_log: Path):
    code, _out, err = run_cli(
        older_than_log, "phase", "add", "P1", "--title", "p", "--allow-older-version"
    )
    assert code == 3 and "--reason" in err
    assert not (older_than_log / ".ddflow" / "events" / "me.jsonl").exists()


def test_the_flag_is_harmless_when_there_is_no_skew(repo: Path):
    code, out, err = run_cli(
        repo, "phase", "add", "P1", "--title", "p", "--allow-older-version", "--reason", "x"
    )
    assert code == 0, (out, err)
    assert kinds(EventLog(repo), "skew.overridden") == []


def _mcp(repo: Path, name: str, args: dict):
    from ddflow.surfaces.mcp import Server

    reply = Server(repo).handle(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": name, "arguments": args},
        }
    )
    return reply["result"]


def test_mcp_refuses_with_exit_3_then_accepts_the_override_argument(older_than_log: Path):
    res = _mcp(older_than_log, "ddflow_phase_add", {"id": "P1", "title": "p", "as_agent": "me"})
    assert res["_meta"]["exit"] == 3, res
    assert "Upgrade ddflow-mcp to >= 99.0.0" in res["content"][0]["text"]
    res = _mcp(
        older_than_log,
        "ddflow_phase_add",
        {"id": "P1", "title": "p", "as_agent": "me", "allow_older_version": "operator said go"},
    )
    assert not res.get("isError"), res
    assert kinds(EventLog(older_than_log, "me"), "skew.overridden")[0].data["reason"] == (
        "operator said go"
    )
    # Reads are never refused.
    assert not _mcp(older_than_log, "ddflow_status", {"as_agent": "other"}).get("isError")


@pytest.mark.parametrize("policy", ["warn", "off"])
def test_warn_and_off_do_not_refuse(older_than_log: Path, monkeypatch, policy: str):
    monkeypatch.setenv("DDFLOW_UPGRADE_SKEW", policy)
    log = EventLog(older_than_log, "me")
    log.append("phase.added", "P1", {"title": "p"})
    assert kinds(log, "skew.overridden") == []
    # The older version still stamps itself, so the log records that it wrote.
    assert fold(log.read_all()).highest_version == "99.0.0"
    assert ddflow.__version__ in fold(log.read_all()).ddflow_versions


def test_the_skew_knob_is_documented_validated_and_settable(repo: Path):
    from ddflow.config import KNOB_DOCS, Config

    assert Config().upgrade.skew == "refuse"
    assert "upgrade.skew" in KNOB_DOCS
    code, _out, err = run_cli(repo, "config", "--set", "upgrade.skew", "sometimes")
    assert code != 0
    code, out, err = run_cli(repo, "config", "--set", "upgrade.skew", "warn")
    assert code == 0, (out, err)
    assert Config.load(repo).upgrade.skew == "warn"


def test_history_and_replay_mark_the_older_versions_events(older_than_log: Path):
    log = EventLog(older_than_log, "me")
    log.override_skew("operator said go")
    log.append("phase.added", "P1", {"title": "first phase"})
    code, out, _err = run_cli(older_than_log, "history")
    assert code == 0
    assert f"[older ddflow {ddflow.__version__}]" in out
    assert "OLDER ddflow let write" in out
    from ddflow.services import sessions as S

    steps = S.replay(log.read_all())
    assert any(s.older == ddflow.__version__ for s in steps)
    assert any("skew override" in s.text for s in steps)
    doc = S.render_reconstruction(fold(log.read_all()), steps)
    assert "written by an older ddflow" in doc


def test_doctor_names_the_versions_and_says_upgrade_not_merge_main(older_than_log: Path):
    log = EventLog(older_than_log, "me")
    log.override_skew("operator said go")
    log.append("phase.added", "P1", {"title": "p"})
    _code, out, _err = run_cli(older_than_log, "doctor")
    assert "99.0.0" in out and ddflow.__version__ in out
    assert "skew override" in out and "operator said go" in out
    assert "event(s) were written by an older ddflow" in out


def test_doctor_advice_for_skipped_kinds_is_to_upgrade(repo: Path):
    shard = repo / ".ddflow" / "events"
    shard.mkdir(parents=True)
    e = Event(
        kind="future.kind",
        subject="X",
        data={},
        agent="future",
        lamport=1,
        ts="2099-01-01T00:00:00Z",
    )
    e = Event(**{**e.__dict__, "id": e.compute_id()})
    (shard / "future.jsonl").write_text(e.to_json() + "\n")
    stamp_newer(repo, "99.0.0", agent="future")
    _code, out, _err = run_cli(repo, "doctor")
    assert "future.kind x1" in out
    # The remedy fits how this ddflow is installed (B-uni-compat-config): a source checkout
    # merges main, an installed one upgrades its package.
    if II.install_info().kind in ("source-tree", "editable"):
        assert "Merge main" in out and "Upgrade ddflow-mcp to" not in out
    else:
        assert "Upgrade ddflow-mcp to >= 99.0.0" in out and "Merge main" not in out


def test_status_json_carries_the_stamped_versions(repo: Path):
    assert run_cli(repo, "init")[0] == 0
    assert run_cli(repo, "phase", "add", "P1", "--title", "p")[0] == 0
    code, out, _err = run_cli(repo, "--json", "status")
    assert code == 0
    assert json.loads(out)["ddflow_version"] == {
        "highest": ddflow.__version__,
        "seen": [ddflow.__version__],
    }


def test_the_highest_stamp_is_the_same_in_any_order_and_ignores_a_nameless_stamp():
    def seen(version, lamport):
        e = Event(
            kind="ddflow.seen",
            subject="ddflow",
            data={"version": version},
            agent="a",
            lamport=lamport,
        )
        return e

    evs = [seen("0.2.0", 1), seen("v0.2.0", 2), seen(None, 3), seen("junk", 4)]
    for order in (evs, evs[::-1]):
        assert fold(list(order)).highest_version == "v0.2.0"
        assert stamp_facts(order, "a", "0.1.0").highest == "v0.2.0"


def test_a_strict_fold_refuses_a_newer_schema_like_an_unknown_kind():
    e = Event(kind="phase.added", subject="P1", data={"title": "p"}, lamport=1, schema=99)
    with pytest.raises(ValueError, match="schema 99"):
        fold([e], strict=True)


def test_override_with_policy_warn_has_nothing_to_override(older_than_log: Path, monkeypatch):
    monkeypatch.setenv("DDFLOW_UPGRADE_SKEW", "warn")
    assert EventLog(older_than_log, "me").override_skew("not needed") is None
    assert kinds(EventLog(older_than_log, "me"), "skew.overridden") == []


def test_the_mcp_override_argument_writes_nothing_when_there_is_no_skew(repo: Path):
    res = _mcp(
        repo,
        "ddflow_phase_add",
        {"id": "P1", "title": "p", "as_agent": "me", "allow_older_version": "x"},
    )
    assert not res.get("isError"), res
    log = EventLog(repo, "me")
    assert kinds(log, "skew.overridden") == []
    assert OLDER_MARK not in kinds(log, "phase.added")[0].data


def test_status_lists_seen_versions_in_version_order(repo: Path, monkeypatch):
    monkeypatch.setenv("DDFLOW_UPGRADE_SKEW", "off")  # the older stamp is written after the newer
    for v in ("0.1.10", "0.1.9"):
        monkeypatch.setattr(ddflow, "__version__", v)
        EventLog(repo, "a").append("phase.added", f"P{v}", {"title": "p"})
    assert run_cli(repo, "init")[0] == 0
    _code, out, _err = run_cli(repo, "--json", "status")
    assert json.loads(out)["ddflow_version"]["seen"][:2] == ["0.1.9", "0.1.10"]


def test_seen_versions_with_equal_keys_keep_a_stable_order(repo: Path, monkeypatch):
    monkeypatch.setenv("DDFLOW_UPGRADE_SKEW", "off")
    for v in ("0.2.0", "0.2"):
        monkeypatch.setattr(ddflow, "__version__", v)
        EventLog(repo, f"a{v}").append("phase.added", f"P{v}", {"title": "p"})
    assert run_cli(repo, "init")[0] == 0
    _code, out, _err = run_cli(repo, "--json", "status")
    assert json.loads(out)["ddflow_version"]["seen"] == ["0.2", "0.2.0"]
