"""Human-readable projections: boards, lessons, and the session brief.

Every file this module writes is **generated** and carries a header saying so. None is
ever parsed back. That single rule removes the entire failure family the projects that
inspired ddflow spent years fighting: markdown that is simultaneously a human document
and a machine record drifts, because humans edit prose and machines edit structure, and
neither notices the other. Here the log is the record and the markdown is a view, so a
stale view is repaired by regenerating it, never by reconciling it.

``brief`` is the load-bearing one. An agent starting a session needs the rules that
apply, the task at hand, and the handful of past lessons that bear on it — and needs
them in roughly a thousand tokens, not the fifteen thousand that reading the corpora
costs. It is retrieval, budgeted, with the budget enforced rather than hoped for.
"""

from __future__ import annotations

import textwrap
from collections.abc import Callable
from pathlib import Path

from ..config import Config
from ..core import provenance as PV
from ..core.model import ABANDONED, BLOCKED, DONE, OUTCOME_MARK, REVIEW, RUNNING, State
from ..core.schedule import Plan, critical_path
from ..core.tier import tier_of

GENERATED = (
    "<!-- GENERATED by `ddflow render`. Do not edit: the event log is the source of truth. -->"
)

# Marks come from model.OUTCOME_MARK -- the board and the gate-status view must agree,
# and two copies of a lookup table are two copies that drift.


def _bar(done: int, total: int, width: int = 18) -> str:
    if total == 0:
        return "─" * width
    filled = round(width * done / total)
    return "█" * filled + "░" * (width - filled)


def _depth(state: State, item, root: str) -> int:
    """How far below the phase this item sits. Bounded, because a parent chain is
    operator-authored and a cycle in it must not hang the renderer."""
    depth, node, seen = 0, item, set()
    while node.parent and node.parent != root and node.parent not in seen:
        seen.add(node.id)
        node = state.items.get(node.parent)
        if node is None:
            break
        depth += 1
    return min(depth, 6)


def unphased(state: State) -> list:
    """Live tasks that sit under no phase, a sub-task after its parent (Bc896ea5d16: the
    board listed only phases' tasks, so a task added with no phase never appeared)."""
    under: set[str] = set()
    for ph in state.phases():
        under |= set(state.descendants(ph.id))
    return _nested(state, "", [t for t in state.tasks() if t.id not in under])


def _nested(state: State, phase: str, tasks: list | None = None) -> list:
    """Tasks under a phase, each sub-task immediately after its parent. ``tasks``
    overrides the set (the unphased ones, whose root is the empty id)."""
    if tasks is None:
        tasks = state.tasks(phase)
    by_parent: dict[str, list] = {}
    for t in tasks:
        by_parent.setdefault(t.parent, []).append(t)
    out: list = []

    def walk(parent: str, seen: set) -> None:
        for t in sorted(by_parent.get(parent, []), key=lambda x: (x.priority, x.id)):
            if t.id in seen:
                continue
            seen.add(t.id)
            out.append(t)
            walk(t.id, seen)

    walk(phase, set())
    # Anything whose parent chain does not reach the phase (an orphan, or a cycle)
    # still belongs on the board: silently dropping it is how work disappears.
    listed = {t.id for t in out}
    out.extend(t for t in tasks if t.id not in listed)
    return out


def board(state: State, cfg: Config | None = None, *, phase: str = "") -> str:
    """The whole queue as a markdown board.

    The gate column is built from the CONFIGURED pipeline. It used to re-type the ten
    default gate ids, so a project that trimmed `gates.task_pipeline` to three got ten
    columns, seven of them permanently blank, under a caption naming gates it does not
    run. Passing `cfg=None` falls back to the defaults for callers that genuinely have
    no config to hand.
    """
    from ..services.gates import pipeline_for

    out = [GENERATED, "", "# Work queue", ""]
    phases = [p for p in state.phases() if not phase or p.id == phase]
    loose = [] if phase else unphased(state)
    if not phases and not loose:
        out.append("_No phases yet. `ddflow phase add <id> --title '...'`_")
        return "\n".join(out)

    def table(tasks: list, root: str) -> None:
        out.append("| | Task | State | Needs | Globs | Gates | Owner |")
        out.append("|---|---|---|---|---|---|---|")
        for t in tasks:
            mark = {DONE: "x", RUNNING: "~", REVIEW: "r", BLOCKED: "!", ABANDONED: "-"}.get(
                t.state, " "
            )
            pipeline = (
                pipeline_for(t, cfg) if cfg is not None else list(Config().gates.task_pipeline)
            )
            gates = "".join(OUTCOME_MARK.get(t.gate_outcome(g), " ") for g in pipeline)
            indent = "&nbsp;&nbsp;&nbsp;&nbsp;" * _depth(state, t, root)
            out.append(
                f"| [{mark}] | {indent}**{t.id}** {t.title} | {t.state} | "
                f"{', '.join(t.needs) or '—'} | {', '.join(f'`{g}`' for g in t.globs) or '—'} | "
                f"`{gates}` | {t.lease.holder if t.lease else '—'} |"
            )
        out.append("")
        caption = " · ".join(
            pipeline_for(tasks[0], cfg) if cfg is not None else list(Config().gates.task_pipeline)
        )
        out.append(
            f"<sub>Gate column order: {caption}. "
            "`x` passed `!` failed `?` unavailable `~` partial `-` skipped</sub>"
        )
        out.append("")

    for ph in sorted(phases, key=lambda p: (p.priority, p.id)):
        # Ordered so a sub-task follows its parent, and indented by depth: a flat list
        # of "P1.T1, P1.T1a, P1.T1b" hides that two of them are halves of the first.
        tasks = _nested(state, ph.id)
        # Abandoned tasks are SETTLED, not outstanding. Counting them in the
        # denominator made a completed phase render as "3/4 tasks", which reads as
        # unfinished work that no longer exists.
        abandoned = [t for t in tasks if t.state == ABANDONED]
        live = [t for t in tasks if t.state != ABANDONED]
        done = sum(1 for t in live if t.state == DONE)
        out.append(f"## {ph.id} — {ph.title or '(untitled)'}")
        out.append("")
        bits = [f"`{ph.state}`", f"{_bar(done, len(live))} {done}/{len(live)} tasks"]
        if abandoned:
            bits.append(f"{len(abandoned)} abandoned")
        if ph.needs:
            bits.append("needs " + ", ".join(f"`{n}`" for n in ph.needs))
        if ph.lease:
            bits.append(f"held by **{ph.lease.holder}**")
        out.append(" · ".join(bits))
        out.append("")
        if ph.body:
            out.append(textwrap.indent(ph.body.strip(), "> "))
            out.append("")
        if tasks:
            table(tasks, ph.id)
    if loose:
        abandoned = [t for t in loose if t.state == ABANDONED]
        live = [t for t in loose if t.state != ABANDONED]
        done = sum(1 for t in live if t.state == DONE)
        out.append("## Unphased — tasks under no phase")
        out.append("")
        bits = [f"{_bar(done, len(live))} {done}/{len(live)} tasks"]
        if abandoned:
            bits.append(f"{len(abandoned)} abandoned")
        out.append(" · ".join(bits))
        out.append("")
        table(loose, "")
    cp = critical_path(state, phase)
    if len(cp) > 1:
        out.append(
            f"**Critical path** ({len(cp)} deep — this, not the task count, "
            f"sets the wall-clock floor): " + " → ".join(f"`{c}`" for c in cp)
        )
        out.append("")
    return "\n".join(out)


def lessons_md(state: State, cfg: Config | None = None) -> str:
    out = [GENERATED, "", "# Lessons", ""]
    live = [x for x in state.lessons.values() if not x.superseded_by]
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    by_tag: dict[str, list] = {}
    for ls in sorted(live, key=lambda x: x.at, reverse=True):
        for tag in ls.tags or ["untagged"]:
            by_tag.setdefault(tag, []).append(ls)
    for tag in sorted(by_tag):
        out.append(f"## {_redact(tag, cfg)}")
        out.append("")
        for ls in by_tag[tag]:
            out.append(f"### {_redact(ls.title, cfg)}")
            out.append("")
            out.append(f"**Rule.** {_redact(ls.rule, cfg)}")
            if ls.why:
                out.append("")
                out.append(f"**Why.** {_redact(ls.why, cfg)}")
            if ls.how:
                out.append("")
                out.append(f"**How to apply.** {_redact(ls.how, cfg)}")
            if ls.seen_in:
                out.append("")
                out.append(f"**Seen in:** {', '.join(_redact(x, cfg) for x in ls.seen_in)}")
            out.append("")
    return "\n".join(out)


def _cell(text: str, cfg: Config | None = None) -> str:
    """One markdown table cell: redacted, newlines folded, `|` escaped so a title cannot
    split the row into extra columns."""
    return _redact(text, cfg).replace("\n", " ").replace("|", "\\|").strip()


def bugs_md(state: State, cfg: Config | None = None) -> str:
    """Every bug, newest change first, with the columns a scanner wants: its state, the
    item it is against, what guards the fix and the lesson the close recorded."""
    out = [GENERATED, "", "# Bugs", ""]
    rows = sorted(
        state.bugs.values(),
        key=lambda b: b.fixed_at or b.invalid_at or b.found_at or "",
        reverse=True,
    )
    if not rows:
        out.append("_None recorded._")
        return "\n".join(out)
    out.append("| Bug | State | Title | Item | Regression tests | Lesson |")
    out.append("|---|---|---|---|---|---|")
    for b in rows:
        tests = ", ".join(_cell(t, cfg) for t in b.regression_tests) or "—"
        out.append(
            f"| {b.id} | {b.resolution or 'open'} | {_cell(b.title or b.summary, cfg)} | "
            f"{b.item or '—'} | {tests} | {b.lesson or '—'} |"
        )
    out.append("")
    return "\n".join(out)


def decisions_md(state: State, cfg: Config | None = None) -> str:
    """The decisions IN FORCE, oldest first -- the order they were made in, which is the
    order the architecture was decided in."""
    out = [GENERATED, "", "# Decisions", ""]
    live = sorted((d for d in state.decisions.values() if d.live), key=lambda d: d.at)
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    for d in live:
        out.append(f"## {d.id} — {_cell(d.title, cfg)}")
        out.append("")
        out.append(_redact(d.decision, cfg))
        if d.globs:
            out.append("")
            out.append(f"**Governs:** {', '.join(_redact(g, cfg) for g in d.globs)}")
        out.append("")
    return "\n".join(out)


def sessions_md(state: State, cfg: Config | None = None) -> str:
    """The sessions, newest first, one line each: when, who, and what it was for."""
    out = [GENERATED, "", "# Sessions", ""]
    rows = sorted(
        state.sessions.values(), key=lambda s: s.ended_at or s.started_at or "", reverse=True
    )
    if not rows:
        out.append("_None recorded._")
        return "\n".join(out)
    for s in rows:
        first = s.prompts[0].get("text", "") if s.prompts else ""
        when = (s.ended_at or s.started_at or "")[:16].replace("T", " ")
        word = "ended" if s.ended_at else "open"
        title = _cell(first, cfg)[:120] or _cell(s.model, cfg)
        out.append(f"- **{s.id}** [{word}] {when} `{s.agent}` {title}")
    out.append("")
    return "\n".join(out)


#: How much of a lesson's rule stands in for a summary it does not have. One paragraph is
#: the unit: the first one, cut at this many characters.
_SUMMARY_FALLBACK_CHARS = 400


def _summary_of(ls, cfg: Config | None = None) -> str:
    if ls.summary:
        return _redact(ls.summary, cfg)
    first = (ls.rule or "").strip().split("\n\n", 1)[0]
    first = " ".join(first.split())
    if len(first) > _SUMMARY_FALLBACK_CHARS:
        first = first[:_SUMMARY_FALLBACK_CHARS].rsplit(" ", 1)[0] + " …"
    return _redact(first, cfg)


def lessons_summary_md(state: State, cfg: Config | None = None) -> str:
    """The distilled rulebook: every live lesson in one paragraph, grouped by tag.

    The file a reader opens INSTEAD of the corpus. Each entry is the lesson's own
    `summary` when it has one, else the first paragraph of its rule -- said, because a
    reader cannot otherwise tell a curated summary from a truncation. `imported` is a
    provenance tag, not a subject, so it never becomes a heading.
    """
    out = [
        GENERATED,
        "",
        "# Lessons — summary",
        "",
        "One paragraph per live lesson; `ddflow recall` or `LESSONS.md` for the full rule. "
        "An entry marked _(first paragraph)_ has no summary of its own yet — "
        "`ddflow lesson add --id <id> --summary ...` gives it one.",
        "",
    ]
    live = [x for x in state.lessons.values() if not x.superseded_by]
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    by_tag: dict[str, list] = {}
    for ls in sorted(live, key=lambda x: x.id):
        subject = [t for t in (ls.tags or []) if t not in ("imported", "summary")]
        by_tag.setdefault(subject[0] if subject else "general", []).append(ls)
    for tag in sorted(by_tag):
        out += [f"## {_redact(tag, cfg)}", ""]
        for ls in by_tag[tag]:
            mark = "" if ls.summary else " _(first paragraph)_"
            out.append(
                f"- **{_redact(ls.title.rstrip('.'), cfg)}.** {_summary_of(ls, cfg)}{mark} `[{ls.id}]`"
            )
        out.append("")
    return "\n".join(out)


def _redact(text: str, cfg: Config | None) -> str:
    """The free text of a record, with secrets and machine-local hosts removed.

    A view is COMMITTED, so a private address a record happened to cite is somebody's
    own service leaked into every clone -- and `test_repo_is_generic` refuses it there
    (bug Bb2c7cdd441). The export documents already ran through this redaction; the
    views did not.
    """
    if not text:
        return text
    # hostname="" and home="": a committed view must be byte-identical on every machine
    # (roborev on 9b6db6bc); the rendering host's own name and $HOME are not inputs. The
    # private addresses, LAN hosts and absolute home paths a record cites are still gone.
    from ..services.export.safe import names_for
    from ..services.redact_report import redact_report

    effective = cfg or Config()
    return redact_report(
        text, hostname="", home="", names=names_for(effective), repo_root="", cfg=effective
    ).text


def research_md(state: State, cfg: Config | None = None) -> str:
    out = [
        GENERATED,
        "",
        "# Research log",
        "",
        "Every entry carries a verdict. An entry with no CONFIRMED or REFUTED label",
        "is a literature summary, not research, and is labelled THEORETICAL.",
        "",
    ]
    if not state.research:
        out.append("_None recorded._")
        return "\n".join(out)
    for r in sorted(state.research.values(), key=lambda x: x.at, reverse=True):
        out.append(f"## {_redact(r.question or r.id, cfg)}")
        out.append("")
        out.append(f"**Verdict: {r.verdict}**" + (f" · item `{r.item}`" if r.item else ""))
        out.append("")
        for label, val in (
            ("Claim", r.claim),
            ("Mechanism", r.mechanism),
            ("Falsifier", r.falsifier),
            ("Budget", r.budget),
        ):
            if val:
                out.append(f"- **{label}.** {_redact(val, cfg)}")
        if r.probe:
            out.append("")
            out.append("**Probe:**")
            out.append("")
            out.append("```console")
            out.append(f"$ {_redact(r.probe, cfg)}")
            if r.probe_output:
                out.append(_redact(r.probe_output.rstrip(), cfg))
            out.append("```")
        if r.sources:
            out.append("")
            out.append("**Sources:** " + ", ".join(_redact(s, cfg) for s in r.sources))
        out.append("")
    return "\n".join(out)


def _approx_tokens(text: str) -> int:
    """Cheap token estimate: ~4 chars per token. Good enough to enforce a budget, and
    it costs no dependency — a tokenizer import here would make the brief the slowest
    command in the tool."""
    return max(1, len(text) // 4)


def _score(x: dict) -> str:
    return f", score {x['score']:.2f}" if isinstance(x.get("score"), int | float) else ""


def _clip(text: str, cap: int) -> str:
    text = (text or "").strip()
    return text if len(text) <= cap else text[: cap - 1].rstrip() + "…"


def _ref(x: dict, key: str) -> str:
    """`B2 [bug open] title`: a linked record, named."""
    tag = " ".join(t for t in (x.get("kind"), x.get("state")) if t)
    return " ".join(p for p in (f"{x[key]}", f"[{tag}]" if tag else "", x.get("title") or "") if p)


def addenda_lines(a: dict) -> list[str]:
    """`show`'s block for one record: what was added to it (verbatim, who, when, score)
    and the links in both directions."""
    out: list[str] = []
    if a["additions"]:
        out.append(f"  additions ({len(a['additions'])}):")
        for x in a["additions"]:
            out.append(f"    {x['at']} by {x['who']}{_score(x)}")
            out += [f"      | {ln}" for ln in (x["text"] or "").splitlines()]
    if a["links"]:
        out.append("  links:")
        out += [
            f"    {x['relation']} {_ref(x, 'target')} (by {x['by']}, {x['at']}{_score(x)})"
            for x in a["links"]
        ]
    if a["linked_from"]:
        out.append("  linked from:")
        out += [
            f"    {_ref(x, 'record')} {x['relation']} this (by {x['by']}, {x['at']}{_score(x)})"
            for x in a["linked_from"]
        ]
    return out


def new_reports_line(item: str, count: int) -> str:
    """The one line heartbeat and `gate status` carry; "" when there is nothing new."""
    if not count:
        return ""
    s = "" if count == 1 else "s"
    return f"{count} new report{s} on {item} since you claimed -- `ddflow show {item}`"


#: At most this many reports are quoted in a brief, each at most this long: the brief has
#: a budget, and the rest is one `show` away.
_REPORTS_SHOWN = 5
_REPORT_CAP = 400


def new_reports_block(item: str, rep: dict) -> str:
    """The brief's lead for a claimed item: the count, then the additions verbatim and the
    records filed against it (because it was claimed or closed)."""
    if not rep["count"]:
        return ""
    s = "" if rep["count"] == 1 else "s"
    lines = [f"## {rep['count']} new report{s} on your item since you claimed", ""]
    entries = [(x["at"], "add", x) for x in rep["additions"]] + [
        (x["at"], "link", x) for x in rep["linked_from"]
    ]
    entries.sort(key=lambda e: e[0])
    for _at, kind, x in entries[:_REPORTS_SHOWN]:
        if kind == "add":
            lines.append(f"- added by {x['who']}{_score(x)}: {_clip(x['text'], _REPORT_CAP)}")
        else:
            lines.append(
                f"- {_ref(x, 'record')} {x['relation']} {item} (by {x['by']}{_score(x)}): "
                f"{_clip(x['text'], _REPORT_CAP)}"
            )
    if len(entries) > _REPORTS_SHOWN:
        lines.append(f"- _{len(entries) - _REPORTS_SHOWN} more: `ddflow show {item}`._")
    return "\n".join(lines) + "\n\n"


#: How many recovery entries of EACH kind the brief spells out; the rest are counted. Per
#: kind, so a run of salvageable trees cannot push a RUNNING item nobody holds, or a tree
#: that could not be measured, off the list (rubber_duck on B20e103326b).
_RECOVERY_SHOWN = 5
_HOLDING, _UNMEASURED, _UNHELD = (
    "holding work",
    "could not be measured",
    "RUNNING with nobody on it",
)


def recovery_band(r) -> str | None:
    """Which band of the brief a recovery entry is named in, in this order: a tree
    holding work, one that COULD NOT be measured (treat as work), an item RUNNING with
    nobody on it; None for a leftover with nothing to salvage, which is counted rather
    than listed (B20e103326b). `recover` and `status` count all three bands as "may
    contain work" (B3f8c406fea): a truthy `salvageable` dropped the unmeasured and the
    unheld. `doctor` makes the two TREE bands a problem and leaves a RUNNING item nobody
    holds a note, since `next` offers it to resume."""
    if r.kind == "stale_running":  # never measured: its `salvageable` says nothing
        return _UNHELD
    if r.salvageable:
        return _HOLDING
    return _UNMEASURED if r.salvageable is None else None


#: The name tests/test_brief_recovery_all.py imports; one function, not a copy.
_recovery_band = recovery_band


def may_hold_work(r) -> bool:
    """A recovery entry that may hold work nobody else has: every band but the quiet one."""
    return recovery_band(r) is not None


def _brief_recovery(out: list[str], recovery: list) -> None:
    bands: dict[str, list] = {_HOLDING: [], _UNMEASURED: [], _UNHELD: []}
    quiet = 0
    for r in sorted(recovery, key=lambda r: (r.kind, r.item)):
        band = recovery_band(r)
        if band is not None:
            bands[band].append(r)
        else:
            quiet += 1
    count = (
        f"{quiet} leftover(s) with nothing to salvage: `ddflow recover` lists them."
        if quiet
        else ""
    )
    if not any(bands.values()):
        if count:
            out += [f"_{count}_", ""]
        return
    out += [
        "## ⚠ Recoverable work found",
        "",
        "Handle these BEFORE starting anything new — a crashed agent's worktree often",
        "holds finished work that exists nowhere else.",
        "",
    ]
    for what, band in bands.items():
        out += [
            f"- **{r.item}** ({r.kind}, was {r.holder}): {r.advice}" for r in band[:_RECOVERY_SHOWN]
        ]
        if len(band) > _RECOVERY_SHOWN:
            more = len(band) - _RECOVERY_SHOWN
            out.append(f"- _{more} more {what}: `ddflow recover` lists them._")
    if count:
        out.append(f"- _{count}_")
    out.append("")


def _brief_current(
    out: list[str],
    state: State,
    cfg: Config,
    item: str,
    repo: Path | None = None,
    *,
    held: list[str] | None = None,
    suggested: bool = False,
    loops: list | None = None,
) -> None:
    """The item this brief is about. "Current" only when it is the agent's own -- named
    with `--item` or held under its lease; the queue's top pick for an agent holding
    nothing is "Suggested next", because calling it Current told an agent it was working
    on something it never claimed (B226d8db6e8)."""
    from ..services.gates import pipeline_for

    it = state.items.get(item)
    if not it:
        return
    held = held or []
    if len(held) > 1:
        out += [
            f"You hold {len(held)} leases: " + ", ".join(f"`{h}`" for h in held) + ". "
            "The most recent claim is below; `ddflow brief --item <id>` for another.",
            "",
        ]
    heading = "Suggested next" if suggested else "Current"
    out += [f"## {heading}: {it.id} — {it.title}", ""]
    if suggested:
        out += ["_You hold no lease. This is the top ready item: `ddflow claim` it first._", ""]
    out.append(
        f"- kind `{it.kind}` · state `{it.state}`"
        + (f" · held by `{it.lease.holder}`" if it.lease else "")
    )
    if it.reopened:
        last = it.reopened[-1]
        out += [
            f"- **REOPENED by verification** ({last['at'][:10]}, {len(it.reopened)}x): "
            f"{last['reason']}",
            *[
                f"  - [{c.get('status', '?')}] {c.get('id', '?')}: {c.get('detail', '')}"
                for c in last["claims"][:5]
            ],
            "  _Its earlier gates were cleared: re-do the work and re-run them._",
        ]
    tier = tier_of(it.tags)
    if tier:
        out.append(f"- tier `{tier}` (advisory: the model to dispatch a subagent on)")
    if it.needs:
        out.append("- needs: " + ", ".join(f"`{n}`" for n in it.needs))
    if it.globs:
        out.append("- writes: " + ", ".join(f"`{g}`" for g in it.globs))
    if it.worktree:
        # Resolved for display: a relative path is portable in the LOG and ambiguous in
        # a brief, where the reader is about to `cd` to it.
        from ..infra.worktree import load_path

        out.append(
            f"- worktree: `{load_path(repo, it.worktree) if repo else it.worktree}`"
            f" on `{it.branch}`"
        )
    todo = [g for g in pipeline_for(it, cfg) if it.gate_outcome(g) not in ("passed", "skipped")]
    out.append("- gates remaining: " + (" → ".join(todo) if todo else "none — ready to complete"))
    if repo is not None and not suggested:
        from ..services.completion import readme_report

        readme = readme_report(state, cfg, item, repo=repo)
        if readme:
            out.append(f"- docs: {readme}")
    for f in loops or []:
        if f.item == item and f.kind == "repeated_failure":
            out.append(f"- {f.render()}")
    if it.body:
        out += ["", textwrap.indent(it.body.strip()[:700], "> ")]
    out.append("")


def cap_held(n: int, others_ready: bool) -> str:
    """ "N more are ready but held by" -- or, with nothing else ready, "N are ready but
    held by": "more" after "Nothing ready" read as a contradiction."""
    return f"{n} {'more ' if others_ready else ''}{'is' if n == 1 else 'are'} ready but held by"


#: How many cap-held ids the brief names before "...".
_CAPPED_SHOWN = 8


def _brief_ready(out: list[str], plan: Plan) -> None:
    out += ["## Ready now", ""]
    if plan.ready:
        for r in plan.ready:
            out.append(
                f"- **{r.id}** — {r.title}"
                + (f" [tier:{tier_of(r.tags)}]" if tier_of(r.tags) else "")
                + (f" (writes {', '.join(r.globs)})" if r.globs else "")
            )
        if len(plan.ready) > 1:
            out += [
                "",
                f"These {len(plan.ready)} are independent: they can run in parallel worktrees.",
            ]
    else:
        out.append("_Nothing ready._")
    if plan.capped:
        # Ready in every sense but the cap: listed apart from "Blocked", where six lines
        # of dependency waits buried them and a reader concluded only the ready few
        # could ever start (Bdcce70d036).
        shown = ", ".join(f"`{i}`" for i in plan.capped[:_CAPPED_SHOWN])
        more = " ..." if len(plan.capped) > _CAPPED_SHOWN else ""
        n = len(plan.capped)
        out += ["", f"{cap_held(n, bool(plan.ready))} {plan.cap_note}: {shown}{more}"]
    blocked = [b for b in plan.blocked if b.item not in set(plan.capped)]
    if blocked:
        out += ["", "## Blocked (and why)", ""]
        out += [f"- `{b.item}` — {b.reason}: {b.detail}" for b in blocked[:6]]


def _brief_decisions(out: list[str], decisions: list) -> None:
    """Architectural decisions governing the current item's files.

    Placed ABOVE lessons on purpose: a decision is binding and a lesson is advice, and
    an agent skimming a brief should meet the binding thing first. Surfaced by glob
    match rather than by search, so a decision reaches whoever is about to write the
    code it governs without their having to suspect it exists.
    """
    if not decisions:
        return
    out += [
        "",
        "## Architectural decisions governing these files",
        "",
        "_Binding unless the operator says otherwise. A superseded decision names "
        "its replacement — follow the replacement._",
        "",
    ]
    for d in decisions:
        # The title and decision are somebody's words: fenced as data, with who recorded
        # them. A decision keeps its status whoever wrote it (D-lean-and-trusted, 3);
        # `trust=` says whether that was the operator.
        line = "- " + PV.fence(
            "decision", d.id, f"**{d.title}** — {d.decision}", PV.decision_origin(d)
        )
        if d.superseded_by:
            line += f"  ⚠ SUPERSEDED by {d.superseded_by}"
        out.append(line)
        if d.alternatives:
            out.append(
                "  - rejected: "
                + PV.fence("decision", d.id, d.alternatives[:160], PV.decision_origin(d))
            )


def _brief_jobs(out: list[str], state: State) -> None:
    """Long-running jobs nobody has recorded as ended, with their LIVE status.

    Right after recovery: a job still running is the most expensive thing to restart by
    accident, and one that died unrecorded is work to collect or redo -- both are what
    the next session must know before it picks anything up.
    """
    from ..services import jobs as J

    pending = [j for j in state.jobs.values() if not j.ended_at]
    if not pending:
        return
    out += ["## Long-running jobs", ""]
    for j in sorted(pending, key=lambda x: x.started_at):
        s = J.status(j)
        tail = {
            "running": "WAIT for it; do not start it again",
            "exited": "collect its result, then `ddflow job end`",
            "gone": "it was killed: find out why before restarting",
            "elsewhere": "check it on that host",
        }.get(s.state, "")
        out.append(f"- **{j.item}** `{j.id}` — {s.state.upper()}: {s.detail}. {tail}")
    out.append("")


def _brief_memories(out: list[str], memories: list) -> None:
    """Operational facts about this machine and repository, newest first.

    After the binding decisions and before the advice: a memory is what the source
    projects' agents were required to read FIRST every session ("this box has 8 H200s",
    "a uniform-zero eval usually means a sidecar 404"), and it costs the next agent a day
    to re-learn one. Said to be partial when it is, so a truncated list is not read as
    the whole store.
    """
    if not memories:
        return
    out += ["", "## Operational memory", "", "_Facts about this machine and repository._", ""]
    for m in memories:
        when = (m.origin_at or m.at)[:10]
        fenced = PV.fence("memory", m.id, m.text, PV.memory_origin(m))
        out.append(f"- {fenced}  `[{m.id}{' ' + when if when else ''}]`")


def _brief_lessons(out: list[str], cfg: Config, lessons: list[dict], state: State) -> None:
    if not lessons:
        return
    out += [
        "",
        "## Lessons that bear on this task",
        "",
        "_Ranked against the task text, not by recency._",
        "",
    ]
    for ls in lessons:
        rule = (ls.get("rule") or "")[: cfg.lessons.snippet_chars]
        rec = state.lessons.get(ls.get("id", ""))
        origin = PV.lesson_origin(rec) if rec else PV.Origin(PV.UNKNOWN)
        out.append(
            "- "
            + PV.fence("lesson", ls.get("id", ""), f"**{ls.get('title', '')}** — {rule}", origin)
        )


def _brief_skills(out: list[str], skills: list) -> None:
    if not skills:
        return
    out += [
        "",
        "## Project skills and rules that bear on this task",
        "",
        "_The project's own; ranked against the task text. Read the file, do not rely on this line._",
        "",
    ]
    out += [e.line() for e in skills]


def brief(  # noqa: PLR0913 -- each section's input, all keyword-only; held/suggested decide the heading
    state: State,
    cfg: Config,
    plan: Plan,
    *,
    repo: Path | None = None,
    item: str = "",
    lessons: list[dict] | None = None,
    skills: list | None = None,
    rules: str = "",
    recovery: list | None = None,
    decisions: list | None = None,
    memories: list | None = None,
    held: list[str] | None = None,
    suggested: bool = False,
    reserve: int = 0,
    loops: list | None = None,
) -> str:
    """The session-start pack, under ``session.brief_max_tokens``.

    Ordered by what an agent must not miss: anything needing rescue first, then what
    it is doing, then what it may do next, then the lessons that bear on it. The budget
    is enforced by truncating from the BOTTOM, so the safety-critical head survives a
    squeeze -- which is why the section order is a correctness property, not layout.
    """
    out: list[str] = ["# ddflow brief", ""]
    _brief_recovery(out, recovery or [])
    _brief_jobs(out, state)
    if item:
        _brief_current(out, state, cfg, item, repo, held=held, suggested=suggested, loops=loops)
    _brief_ready(out, plan)
    _brief_decisions(out, decisions or [])
    # `memories` is every LIVE one, newest first; how many to show is this view's call.
    shown = (memories or [])[: cfg.memory.brief_items]
    _brief_memories(out, shown)
    if shown and len(memories or []) > len(shown):
        out.append(
            f"- _{len(memories or []) - len(shown)} more: `ddflow memory list`, or "
            f"`ddflow recall <topic>`._"
        )
    if rules:
        out += ["", "## Project rules", "", rules.strip()]
    _brief_lessons(out, cfg, lessons or [], state)
    _brief_skills(out, skills or [])

    if any(PV.TAG in line for line in out):
        out[1:1] = [f"_{PV.DATA_RULE}_", ""]
    text = "\n".join(out)
    # `reserve`: tokens a caller will PREPEND (the new-reports block), so the whole stays
    # inside the budget and it is the bottom that gives way.
    budget = max(1, cfg.session.brief_max_tokens - reserve)
    if _approx_tokens(text) > budget:
        text = text[: budget * 4].rsplit("\n", 1)[0]
        text += (
            f"\n\n_[brief truncated at {budget} tokens "
            f"(session.brief_max_tokens); `ddflow show <id>` for detail]_"
        )
    return text


#: Every generated view: its filename and how to render it. The ONE map. There were two
#: -- this function's and a copy in `sessions.bundle` whose docstring said it used this
#: one -- and the copy already wrote different bytes. The pre-commit check
#: (`services/enforce.py::check_views`) reads it too, so a view added here is checked
#: without anyone remembering to.
VIEWS: tuple[tuple[str, Callable[[State, Config | None], str]], ...] = (
    ("QUEUE.md", board),
    ("LESSONS.md", lessons_md),
    ("LESSONS-SUMMARY.md", lessons_summary_md),
    ("RESEARCH.md", research_md),
)


def render_views(state: State, cfg: Config | None = None) -> dict[str, str]:
    """filename -> the exact text a view file must hold for this state."""
    return {name: fn(state, cfg).rstrip() + "\n" for name, fn in VIEWS}


def write_views(
    root: Path, state: State, cfg: Config | None = None, *, subdir: str = "docs/ddflow"
) -> list[Path]:
    """Regenerate every human view. Same state in, same bytes out -- which the commit
    hook now HOLDS it to (B18): a staged view that differs from this is refused."""
    d = Path(root) / subdir
    d.mkdir(parents=True, exist_ok=True)
    written = []
    for name, new in render_views(state, cfg).items():
        p = d / name
        if not p.exists() or p.read_text("utf-8") != new:
            p.write_text(new, "utf-8")
        written.append(p)
    return written
