"""Human-readable projections: boards, lessons, and the session brief.

Every file this module writes is **generated** and carries a header saying so. None is
ever parsed back. That single rule removes the entire failure family the projects that
inspired ddflow spent years fighting: markdown that is simultaneously a human document
and a machine record drifts, because humans edit prose and machines edit structure, and
neither notices the other. Here the log is the record and the markdown is a view, so a
stale view is repaired by regenerating it, never by reconciling it.

``brief`` is the load-bearing one. An agent starting a session needs the rules that
apply, the task at hand, and the handful of past lessons that bear on it — and needs
them in roughly a thousand tokens, not the fifteen thousand that reading the corpora
costs. It is retrieval, budgeted, with the budget enforced rather than hoped for.
"""

from __future__ import annotations

import re
import textwrap
from collections.abc import Callable
from pathlib import Path

from ..config import Config
from ..core import clock
from ..core import progress as PR
from ..core import provenance as PV
from ..core.model import ABANDONED, BLOCKED, DONE, OUTCOME_MARK, REVIEW, RUNNING, State
from ..core.schedule import Plan, critical_path
from ..core.tier import tier_of
from ..services.redact_report import redactor

GENERATED = (
    "<!-- GENERATED by `ddflow render`. Do not edit: the event log is the source of truth. -->"
)

# Marks come from model.OUTCOME_MARK -- the board and the gate-status view must agree,
# and two copies of a lookup table are two copies that drift.


def _bar(done: int, total: int, width: int = 18) -> str:
    if total == 0:
        return "─" * width
    filled = round(width * done / total)
    return "█" * filled + "░" * (width - filled)


# The board's structure lives in core.progress (B-uni-tallies): the markdown here and the
# `board --json` rows are rendered from the one `board_rows`. Re-exported under the old
# names, which other modules import.
_depth = PR.depth
_nested = PR.nested
unphased = PR.unphased


def board(state: State, cfg: Config | None = None, *, phase: str = "") -> str:
    """The whole queue as a markdown board.

    The gate column is built from the CONFIGURED pipeline. It used to re-type the ten
    default gate ids, so a project that trimmed `gates.task_pipeline` to three got ten
    columns, seven of them permanently blank, under a caption naming gates it does not
    run. Passing `cfg=None` falls back to the defaults for callers that genuinely have
    no config to hand.
    """
    from ..services.gates import pipeline_for

    out = [GENERATED, "", "# Work queue", ""]
    default = list(Config().gates.task_pipeline)
    sections = PR.board_rows(
        state, (lambda t: pipeline_for(t, cfg)) if cfg is not None else (lambda t: default), phase
    )
    if not sections:
        out.append("_No phases yet. `ddflow phase add <id> --title '...'`_")
        return "\n".join(out)

    def table(rows: list[dict]) -> None:
        out.append("| | Task | State | Needs | Globs | Gates | Owner |")
        out.append("|---|---|---|---|---|---|---|")
        for r in rows:
            mark = {DONE: "x", RUNNING: "~", REVIEW: "r", BLOCKED: "!", ABANDONED: "-"}.get(
                r["state"], " "
            )
            gates = "".join(OUTCOME_MARK.get(o, " ") for o in r["gates"].values())
            indent = "&nbsp;&nbsp;&nbsp;&nbsp;" * r["depth"]
            # Every free-text cell goes through _cell (B2eaa1e5e8e): a `|` in a title
            # invented a column and a newline split the row.
            needs = ", ".join(_cell(n, cfg) for n in r["needs"]) or "—"
            globs = ", ".join(f"`{_cell(g, cfg)}`" for g in r["globs"]) or "—"
            owner = _cell(r["owner"], cfg) if r["owner"] else "—"
            out.append(
                f"| [{mark}] | {indent}**{_id_cell(r['id'], cfg)}** {_cell(r['title'], cfg)} | "
                f"{r['state']} | {needs} | {globs} | `{gates}` | {owner} |"
            )
        out.append("")
        caption = " · ".join(rows[0]["gates"])
        out.append(
            f"<sub>Gate column order: {caption}. "
            "`x` passed `!` failed `?` unavailable `~` partial `-` skipped</sub>"
        )
        out.append("")

    for sec in sections:
        # Ordered so a sub-task follows its parent, and indented by depth: a flat list
        # of "P1.T1, P1.T1a, P1.T1b" hides that two of them are halves of the first.
        # Abandoned tasks are SETTLED, not outstanding: out of the total (core.progress).
        n = sec.tally
        ph = sec.phase
        if ph is None:
            out.append("## Unphased — tasks under no phase")
            out.append("")
            bits = []
        else:
            out.append(f"## {ph.id} — {ph.title or '(untitled)'}")
            out.append("")
            bits = [f"`{ph.state}`"]
        bits.append(f"{_bar(n.done, n.live)} {n.done}/{n.live} tasks")
        if n.abandoned:
            bits.append(f"{n.abandoned} abandoned")
        if ph is not None and ph.needs:
            bits.append("needs " + ", ".join(f"`{x}`" for x in ph.needs))
        if ph is not None and ph.lease:
            bits.append(f"held by **{ph.lease.holder}**")
        out.append(" · ".join(bits))
        out.append("")
        if ph is not None and ph.body:
            out.append(textwrap.indent(ph.body.strip(), "> "))
            out.append("")
        if sec.rows:
            table(sec.rows)
    cp = critical_path(state, phase)
    if len(cp) > 1:
        out.append(
            f"**Critical path** ({len(cp)} deep — this, not the task count, "
            f"sets the wall-clock floor): " + " → ".join(f"`{c}`" for c in cp)
        )
        out.append("")
    return "\n".join(out)


def lessons_md(state: State, cfg: Config | None = None) -> str:
    out = [GENERATED, "", "# Lessons", ""]
    live = [x for x in state.lessons.values() if not x.superseded_by]
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    by_tag: dict[str, list] = {}
    for ls in sorted(live, key=lambda x: x.at, reverse=True):
        for tag in ls.tags or ["untagged"]:
            by_tag.setdefault(tag, []).append(ls)
    for tag in sorted(by_tag):
        out.append(f"## {_redact(tag, cfg)}")
        out.append("")
        for ls in by_tag[tag]:
            out.append(f"### {_redact(ls.title, cfg)}")
            out.append("")
            out.append(f"**Rule.** {_redact(ls.rule, cfg)}")
            if ls.why:
                out.append("")
                out.append(f"**Why.** {_redact(ls.why, cfg)}")
            if ls.how:
                out.append("")
                out.append(f"**How to apply.** {_redact(ls.how, cfg)}")
            if ls.seen_in:
                out.append("")
                out.append(f"**Seen in:** {', '.join(_redact(x, cfg) for x in ls.seen_in)}")
            out.append("")
    return "\n".join(out)


def _fold(text: str, cfg: Config | None = None) -> str:
    """Redacted, with every CommonMark line ending (LF, CR, CRLF) folded to a space: the
    part of a table cell's escaping every cell shares."""
    return re.sub(r"\r\n?|\n", " ", _redact(text, cfg))


def _cell(text: str, cfg: Config | None = None) -> str:
    """One markdown table cell: redacted, line breaks folded, `|` escaped so a title
    cannot split the row into extra columns (B2eaa1e5e8e).

    Every CommonMark line ending is folded -- a lone CR is one too, and a raw one split
    the row just like LF. A GFM row splitter reads a doubled backslash as an escaped
    backslash, so the backslashes right before a `|` are doubled too: `a\\|b` written as
    `a\\\\|b` left the pipe a delimiter again (roborev on fix-B2eaa1e5e8e). Nothing else
    is escaped: a title is markdown (its backticks are meant), and escaping every
    backslash turned an author's `\\*x\\*` into emphasis (roborev on 72565c2d).
    """
    return re.sub(r"(\\*)\|", lambda m: m.group(1) * 2 + "\\|", _fold(text, cfg)).strip()


def _id_cell(text: str, cfg: Config | None = None) -> str:
    """An item id for the board, where the row wraps it in `**...**`. An id is a literal
    name, not markdown: a backslash or `*` in it closed or broke the bold span and
    re-parsed the rest of the row (roborev on ded56144), so those, backticks and the
    pipe are all escaped."""
    return re.sub(r"([\\*`|])", r"\\\1", _fold(text, cfg)).strip()


def bugs_md(state: State, cfg: Config | None = None) -> str:
    """Every bug, newest change first, with the columns a scanner wants: its state, the
    item it is against, what guards the fix and the lesson the close recorded."""
    out = [GENERATED, "", "# Bugs", ""]
    rows = sorted(
        state.bugs.values(),
        key=lambda b: b.fixed_at or b.invalid_at or b.found_at or "",
        reverse=True,
    )
    if not rows:
        out.append("_None recorded._")
        return "\n".join(out)
    out.append("| Bug | State | Title | Item | Regression tests | Lesson |")
    out.append("|---|---|---|---|---|---|")
    for b in rows:
        tests = ", ".join(_cell(t, cfg) for t in b.regression_tests) or "—"
        out.append(
            f"| {b.id} | {b.resolution or 'open'} | {_cell(b.title or b.summary, cfg)} | "
            f"{_cell(b.item, cfg) or '—'} | {tests} | {_cell(b.lesson, cfg) or '—'} |"
        )
    out.append("")
    return "\n".join(out)


def decisions_md(state: State, cfg: Config | None = None) -> str:
    """The decisions IN FORCE, oldest first -- the order they were made in, which is the
    order the architecture was decided in."""
    out = [GENERATED, "", "# Decisions", ""]
    live = sorted((d for d in state.decisions.values() if d.live), key=lambda d: d.at)
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    for d in live:
        out.append(f"## {d.id} — {_cell(d.title, cfg)}")
        out.append("")
        out.append(_redact(d.decision, cfg))
        if d.globs:
            out.append("")
            out.append(f"**Governs:** {', '.join(_redact(g, cfg) for g in d.globs)}")
        out.append("")
    return "\n".join(out)


def sessions_md(state: State, cfg: Config | None = None) -> str:
    """The sessions, newest first, one line each: when, who, and what it was for."""
    out = [GENERATED, "", "# Sessions", ""]
    rows = sorted(
        state.sessions.values(), key=lambda s: s.ended_at or s.started_at or "", reverse=True
    )
    if not rows:
        out.append("_None recorded._")
        return "\n".join(out)
    for s in rows:
        first = s.prompts[0].get("text", "") if s.prompts else ""
        when = clock.fmt_minute(s.ended_at or s.started_at or "")
        word = "ended" if s.ended_at else "open"
        title = _cell(first, cfg)[:120] or _cell(s.model, cfg)
        out.append(f"- **{s.id}** [{word}] {when} `{s.agent}` {title}")
    out.append("")
    return "\n".join(out)


#: How much of a lesson's rule stands in for a summary it does not have. One paragraph is
#: the unit: the first one, cut at this many characters.
_SUMMARY_FALLBACK_CHARS = 400


def _summary_of(ls, cfg: Config | None = None) -> str:
    if ls.summary:
        return _redact(ls.summary, cfg)
    first = (ls.rule or "").strip().split("\n\n", 1)[0]
    first = " ".join(first.split())
    if len(first) > _SUMMARY_FALLBACK_CHARS:
        first = first[:_SUMMARY_FALLBACK_CHARS].rsplit(" ", 1)[0] + " …"
    return _redact(first, cfg)


def lessons_summary_md(state: State, cfg: Config | None = None) -> str:
    """The distilled rulebook: every live lesson in one paragraph, grouped by tag.

    The file a reader opens INSTEAD of the corpus. Each entry is the lesson's own
    `summary` when it has one, else the first paragraph of its rule -- said, because a
    reader cannot otherwise tell a curated summary from a truncation. `imported` is a
    provenance tag, not a subject, so it never becomes a heading.
    """
    out = [
        GENERATED,
        "",
        "# Lessons — summary",
        "",
        "One paragraph per live lesson; `ddflow recall` or `LESSONS.md` for the full rule. "
        "An entry marked _(first paragraph)_ has no summary of its own yet — "
        "`ddflow lesson add --id <id> --summary ...` gives it one.",
        "",
    ]
    live = [x for x in state.lessons.values() if not x.superseded_by]
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    by_tag: dict[str, list] = {}
    for ls in sorted(live, key=lambda x: x.id):
        subject = [t for t in (ls.tags or []) if t not in ("imported", "summary")]
        by_tag.setdefault(subject[0] if subject else "general", []).append(ls)
    for tag in sorted(by_tag):
        out += [f"## {_redact(tag, cfg)}", ""]
        for ls in by_tag[tag]:
            mark = "" if ls.summary else " _(first paragraph)_"
            out.append(
                f"- **{_redact(ls.title.rstrip('.'), cfg)}.** {_summary_of(ls, cfg)}{mark} `[{ls.id}]`"
            )
        out.append("")
    return "\n".join(out)


def _redact(text: str, cfg: Config | None) -> str:
    """The free text of a record, with secrets and machine-local hosts removed.

    A view is COMMITTED, so a private address a record happened to cite is somebody's
    own service leaked into every clone -- and `test_repo_is_generic` refuses it there
    (bug Bb2c7cdd441). The export documents already ran through this redaction; the
    views did not.
    """
    if not text:
        return text
    # hostname="" and home="": a committed view must be byte-identical on every machine
    # (roborev on 9b6db6bc); the rendering host's own name and $HOME are not inputs. The
    # private addresses, LAN hosts and absolute home paths a record cites are still gone.
    return redactor("view", cfg or Config()).text(text).text


def research_md(state: State, cfg: Config | None = None) -> str:
    out = [
        GENERATED,
        "",
        "# Research log",
        "",
        "Every entry carries a verdict. An entry with no CONFIRMED or REFUTED label",
        "is a literature summary, not research, and is labelled THEORETICAL.",
        "",
    ]
    if not state.research:
        out.append("_None recorded._")
        return "\n".join(out)
    for r in sorted(state.research.values(), key=lambda x: x.at, reverse=True):
        out.append(f"## {_redact(r.question or r.id, cfg)}")
        out.append("")
        out.append(f"**Verdict: {r.verdict}**" + (f" · item `{r.item}`" if r.item else ""))
        out.append("")
        for label, val in (
            ("Claim", r.claim),
            ("Mechanism", r.mechanism),
            ("Falsifier", r.falsifier),
            ("Budget", r.budget),
        ):
            if val:
                out.append(f"- **{label}.** {_redact(val, cfg)}")
        if r.probe:
            out.append("")
            out.append("**Probe:**")
            out.append("")
            out.append("```console")
            out.append(f"$ {_redact(r.probe, cfg)}")
            if r.probe_output:
                out.append(_redact(r.probe_output.rstrip(), cfg))
            out.append("```")
        if r.sources:
            out.append("")
            out.append("**Sources:** " + ", ".join(_redact(s, cfg) for s in r.sources))
        out.append("")
    return "\n".join(out)


def _approx_tokens(text: str) -> int:
    """Cheap token estimate: ~4 chars per token. Good enough to enforce a budget, and
    it costs no dependency — a tokenizer import here would make the brief the slowest
    command in the tool."""
    return max(1, len(text) // 4)


def _score(x: dict) -> str:
    return f", score {x['score']:.2f}" if isinstance(x.get("score"), int | float) else ""


def _clip(text: str, cap: int) -> str:
    text = (text or "").strip()
    return text if len(text) <= cap else text[: cap - 1].rstrip() + "…"


def _ref(x: dict, key: str) -> str:
    """`B2 [bug open] title`: a linked record, named."""
    tag = " ".join(t for t in (x.get("kind"), x.get("state")) if t)
    return " ".join(p for p in (f"{x[key]}", f"[{tag}]" if tag else "", x.get("title") or "") if p)


def addenda_lines(a: dict) -> list[str]:
    """`show`'s block for one record: what was added to it (verbatim, who, when, score)
    and the links in both directions."""
    out: list[str] = []
    if a["additions"]:
        out.append(f"  additions ({len(a['additions'])}):")
        for x in a["additions"]:
            out.append(f"    {x['at']} by {x['who']}{_score(x)}")
            out += [f"      | {ln}" for ln in (x["text"] or "").splitlines()]
    if a["links"]:
        out.append("  links:")
        out += [
            f"    {x['relation']} {_ref(x, 'target')} (by {x['by']}, {x['at']}{_score(x)})"
            + _reason(x)
            for x in a["links"]
        ]
    if a.get("dismissals"):
        out.append("  dismissed as distinct:")
        out += [
            f"    {_ref(x, 'target')} (by {x['by']}, {x['at']})" + _reason(x)
            for x in a["dismissals"]
        ]
    if a["linked_from"]:
        out.append("  linked from:")
        out += [
            f"    {_ref(x, 'record')} {x['relation']} this (by {x['by']}, {x['at']}{_score(x)})"
            + _reason(x)
            for x in a["linked_from"]
        ]
    return out


def _reason(x: dict) -> str:
    """A link's `--reason`, as a trailing ` -- <why>`; "" when none was given."""
    why = (x.get("reason") or "").strip()
    return f" -- {why}" if why else ""


def new_reports_line(item: str, count: int) -> str:
    """The one line heartbeat and `gate status` carry; "" when there is nothing new."""
    if not count:
        return ""
    s = "" if count == 1 else "s"
    return f"{count} new report{s} on {item} since you claimed -- `ddflow show {item}`"


#: At most this many reports are quoted in a brief, each at most this long: the brief has
#: a budget, and the rest is one `show` away.
_REPORTS_SHOWN = 5
_REPORT_CAP = 400


def new_reports_block(item: str, rep: dict) -> str:
    """The brief's lead for a claimed item: the count, then the additions verbatim and the
    records filed against it (because it was claimed or closed)."""
    if not rep["count"]:
        return ""
    s = "" if rep["count"] == 1 else "s"
    lines = [f"## {rep['count']} new report{s} on your item since you claimed", ""]
    entries = [(x["at"], "add", x) for x in rep["additions"]] + [
        (x["at"], "link", x) for x in rep["linked_from"]
    ]
    entries.sort(key=lambda e: e[0])
    for _at, kind, x in entries[:_REPORTS_SHOWN]:
        if kind == "add":
            lines.append(f"- added by {x['who']}{_score(x)}: {_clip(x['text'], _REPORT_CAP)}")
        else:
            lines.append(
                f"- {_ref(x, 'record')} {x['relation']} {item} (by {x['by']}{_score(x)}): "
                f"{_clip(x['text'], _REPORT_CAP)}"
            )
    if len(entries) > _REPORTS_SHOWN:
        lines.append(f"- _{len(entries) - _REPORTS_SHOWN} more: `ddflow show {item}`._")
    return "\n".join(lines) + "\n\n"


#: How many recovery entries of EACH kind the brief spells out; the rest are counted. Per
#: kind, so a run of salvageable trees cannot push a RUNNING item nobody holds, or a tree
#: that could not be measured, off the list (rubber_duck on B20e103326b).
_RECOVERY_SHOWN = 5
_HOLDING, _UNMEASURED, _UNHELD = (
    "holding work",
    "could not be measured",
    "RUNNING with nobody on it",
)


def recovery_band(r) -> str | None:
    """Which band of the brief a recovery entry is named in, in this order: a tree
    holding work, one that COULD NOT be measured (treat as work), an item RUNNING with
    nobody on it; None for a leftover with nothing to salvage, which is counted rather
    than listed (B20e103326b). `recover` and `status` count all three bands as "may
    contain work" (B3f8c406fea): a truthy `salvageable` dropped the unmeasured and the
    unheld. `doctor` makes the two TREE bands a problem and leaves a RUNNING item nobody
    holds a note, since `next` offers it to resume."""
    if r.kind == "stale_running":  # never measured: its `salvageable` says nothing
        return _UNHELD
    if r.salvageable:
        return _HOLDING
    return _UNMEASURED if r.salvageable is None else None


#: The name tests/test_brief_recovery_all.py imports; one function, not a copy.
_recovery_band = recovery_band


def may_hold_work(r) -> bool:
    """A recovery entry that may hold work nobody else has: every band but the quiet one."""
    return recovery_band(r) is not None


def _brief_recovery(out: list[str], recovery: list) -> None:
    bands: dict[str, list] = {_HOLDING: [], _UNMEASURED: [], _UNHELD: []}
    quiet = 0
    for r in sorted(recovery, key=lambda r: (r.kind, r.item)):
        band = recovery_band(r)
        if band is not None:
            bands[band].append(r)
        else:
            quiet += 1
    count = (
        f"{quiet} leftover(s) with nothing to salvage: `ddflow recover` lists them."
        if quiet
        else ""
    )
    if not any(bands.values()):
        if count:
            out += [f"_{count}_", ""]
        return
    out += [
        "## ⚠ Recoverable work found",
        "",
        "Handle these BEFORE starting anything new — a crashed agent's worktree often",
        "holds finished work that exists nowhere else.",
        "",
    ]
    for what, band in bands.items():
        out += [
            f"- **{r.item}** ({r.kind}, was {r.holder}): {r.advice}" for r in band[:_RECOVERY_SHOWN]
        ]
        if len(band) > _RECOVERY_SHOWN:
            more = len(band) - _RECOVERY_SHOWN
            out.append(f"- _{more} more {what}: `ddflow recover` lists them._")
    if count:
        out.append(f"- _{count}_")
    out.append("")


def _brief_current(
    out: list[str],
    state: State,
    cfg: Config,
    item: str,
    repo: Path | None = None,
    *,
    held: list[str] | None = None,
    suggested: bool = False,
    loops: list | None = None,
) -> None:
    """The item this brief is about. "Current" only when it is the agent's own -- named
    with `--item` or held under its lease; the queue's top pick for an agent holding
    nothing is "Suggested next", because calling it Current told an agent it was working
    on something it never claimed (B226d8db6e8)."""
    from ..services.gates import pipeline_for

    it = state.items.get(item)
    if not it:
        return
    held = held or []
    if len(held) > 1:
        out += [
            f"You hold {len(held)} leases: " + ", ".join(f"`{h}`" for h in held) + ". "
            "The most recent claim is below; `ddflow brief --item <id>` for another.",
            "",
        ]
    heading = "Suggested next" if suggested else "Current"
    out += [f"## {heading}: {it.id} — {it.title}", ""]
    if suggested:
        out += ["_You hold no lease. This is the top ready item: `ddflow claim` it first._", ""]
    out.append(
        f"- kind `{it.kind}` · state `{it.state}`"
        + (f" · held by `{it.lease.holder}`" if it.lease else "")
    )
    if it.reopened:
        last = it.reopened[-1]
        out += [
            f"- **REOPENED by verification** ({clock.fmt_date(last['at'])}, {len(it.reopened)}x): "
            f"{last['reason']}",
            *[
                f"  - [{c.get('status', '?')}] {c.get('id', '?')}: {c.get('detail', '')}"
                for c in last["claims"][:5]
            ],
            "  _Its earlier gates were cleared: re-do the work and re-run them._",
        ]
    tier = tier_of(it.tags)
    if tier:
        out.append(f"- tier `{tier}` (advisory: the model to dispatch a subagent on)")
    if it.needs:
        out.append("- needs: " + ", ".join(f"`{n}`" for n in it.needs))
    if it.globs:
        out.append("- writes: " + ", ".join(f"`{g}`" for g in it.globs))
    if it.worktree:
        # Resolved for display: a relative path is portable in the LOG and ambiguous in
        # a brief, where the reader is about to `cd` to it.
        from ..infra.worktree import load_path

        out.append(
            f"- worktree: `{load_path(repo, it.worktree) if repo else it.worktree}`"
            f" on `{it.branch}`"
        )
    todo = [g for g in pipeline_for(it, cfg) if it.gate_outcome(g) not in ("passed", "skipped")]
    out.append("- gates remaining: " + (" → ".join(todo) if todo else "none — ready to complete"))
    if repo is not None and not suggested:
        from ..services.completion import readme_report

        readme = readme_report(state, cfg, item, repo=repo)
        if readme:
            out.append(f"- docs: {readme}")
    for f in loops or []:
        if f.item == item and f.kind == "repeated_failure":
            out.append(f"- {f.render()}")
    if it.body:
        out += ["", textwrap.indent(it.body.strip()[:700], "> ")]
    out.append("")


def cap_held(n: int, others_ready: bool) -> str:
    """ "N more are ready but held by" -- or, with nothing else ready, "N are ready but
    held by": "more" after "Nothing ready" read as a contradiction."""
    return f"{n} {'more ' if others_ready else ''}{'is' if n == 1 else 'are'} ready but held by"


#: How many cap-held ids the brief names before "...".
_CAPPED_SHOWN = 8


def _brief_ready(out: list[str], plan: Plan) -> None:
    out += ["## Ready now", ""]
    if plan.ready:
        for r in plan.ready:
            out.append(
                f"- **{r.id}** — {r.title}"
                + (f" [tier:{tier_of(r.tags)}]" if tier_of(r.tags) else "")
                + (f" (writes {', '.join(r.globs)})" if r.globs else "")
            )
        if len(plan.ready) > 1:
            out += [
                "",
                f"These {len(plan.ready)} are independent: they can run in parallel worktrees.",
            ]
    else:
        out.append("_Nothing ready._")
    if plan.parallel_line:
        out += ["", plan.parallel_line]
    if plan.capped:
        # Ready in every sense but the cap: listed apart from "Blocked", where six lines
        # of dependency waits buried them and a reader concluded only the ready few
        # could ever start (Bdcce70d036).
        shown = ", ".join(f"`{i}`" for i in plan.capped[:_CAPPED_SHOWN])
        more = " ..." if len(plan.capped) > _CAPPED_SHOWN else ""
        n = len(plan.capped)
        out += ["", f"{cap_held(n, bool(plan.ready))} {plan.cap_note}: {shown}{more}"]
    blocked = [b for b in plan.blocked if b.item not in set(plan.capped)]
    if blocked:
        out += ["", "## Blocked (and why)", ""]
        out += [f"- `{b.item}` — {b.reason}: {b.detail}" for b in blocked[:6]]


#: How much of a decision's text the brief quotes; `ddflow decision show` has the rest.
BRIEF_DECISION_CHARS = 280


def _brief_decisions(out: list[str], decisions: list) -> None:
    """Architectural decisions governing the current item's files.

    Placed ABOVE lessons on purpose: a decision is binding and a lesson is advice, and
    an agent skimming a brief should meet the binding thing first. Surfaced by glob
    match rather than by search, so a decision reaches whoever is about to write the
    code it governs without their having to suspect it exists.
    """
    if not decisions:
        return
    out += [
        "",
        "## Architectural decisions governing these files",
        "",
        "_Binding unless the operator says otherwise. A superseded decision names "
        "its replacement — follow the replacement._",
        "",
    ]
    if any(len(d.decision) > BRIEF_DECISION_CHARS for d in decisions):
        out += [
            f"_Each is cut at {BRIEF_DECISION_CHARS} characters: `ddflow decision show <id>` "
            "for the whole of one._",
            "",
        ]
    for d in decisions:
        # The title and decision are somebody's words: fenced as data, with who recorded
        # them. A decision keeps its status whoever wrote it (D-lean-and-trusted, 3);
        # `trust=` says whether that was the operator. Cut BEFORE fencing (B1472311a63):
        # one decision ran to 2301 characters, half the whole brief's budget.
        text = d.decision
        if len(text) > BRIEF_DECISION_CHARS:
            text = text[:BRIEF_DECISION_CHARS].rsplit(" ", 1)[0] + " …"
        line = "- " + PV.fence("decision", d.id, f"**{d.title}** — {text}", PV.decision_origin(d))
        if d.superseded_by:
            line += f"  ⚠ SUPERSEDED by {d.superseded_by}"
        out.append(line)
        if d.alternatives:
            out.append(
                "  - rejected: "
                + PV.fence("decision", d.id, d.alternatives[:160], PV.decision_origin(d))
            )


#: How many of other items' jobs on another host every brief lists in full, and how many
#: of their exited or killed jobs a brief about NO item (nothing held, nothing ready)
#: lists; the rest of each collapse to one count line. A brief about an item -- named,
#: held or suggested -- lists none of the exited or killed ones.
BRIEF_OTHER_JOBS = 5


def _brief_jobs(out: list[str], state: State, item: str = "", agent: str = "") -> None:
    """Long-running jobs nobody has recorded as ended, with their LIVE status.

    Right after recovery: a job still running is the most expensive thing to restart by
    accident, and one that died unrecorded is work to collect or redo -- both are what
    the next session must know before it picks anything up.

    Bounded (B8114a8b531): a job running here, every job of the item the brief is
    about and every job the brief's own ``agent`` started (B1472311a63) are listed in
    full. Other items' jobs on another host (they may be running,
    nothing here can tell) are listed up to ``BRIEF_OTHER_JOBS``, newest first; their
    exited or killed jobs -- dozens, in a long-lived project -- are listed only by a brief
    about no item, and the rest of each kind collapse to one count line. Listed one by
    one they filled the whole token budget ahead of the item's own section, and the
    brief was cut before it said anything about the item.
    """
    from ..services import jobs as J

    pending = [j for j in state.jobs.values() if not j.ended_at]
    if not pending:
        return
    shown: list = []
    remote: list = []  # other items' jobs on another host: may be running
    stale: list = []  # other items' jobs that exited or were killed
    for j in sorted(pending, key=lambda x: x.started_at):
        s = J.status(j)
        if s.state == "running" or (item and j.item == item) or (agent and j.by == agent):
            shown.append((j, s))
        else:
            (remote if s.state == "elsewhere" else stale).append((j, s))
    keep_stale = 0 if item else BRIEF_OTHER_JOBS
    for bucket, keep in ((remote, BRIEF_OTHER_JOBS), (stale, keep_stale)):
        shown += bucket[len(bucket) - min(keep, len(bucket)) :]  # the newest `keep`
    # The item's own jobs first, then the agent's own: when the section is cut to its
    # share, the end goes first.
    shown.sort(
        key=lambda js: (
            not (item and js[0].item == item),
            not (agent and js[0].by == agent),
            js[0].started_at,
        )
    )
    out += ["## Long-running jobs", ""]
    for j, s in shown:
        tail = {
            "running": "WAIT for it; do not start it again",
            "exited": "collect its result, then `ddflow job end`",
            "gone": "it was killed: find out why before restarting",
            "elsewhere": "check it on that host",
        }.get(s.state, "")
        out.append(f"- **{j.item}** `{j.id}` — {s.state.upper()}: {s.detail}. {tail}")
    if hidden := len(remote) - min(BRIEF_OTHER_JOBS, len(remote)):
        out.append(
            f"- _{hidden} more job(s) of other items on other hosts (they may be running): "
            "`ddflow job list` shows them; check each on its host before restarting it._"
        )
    if hidden := len(stale) - min(keep_stale, len(stale)):
        whose = "other items'" if item else "older"
        out.append(
            f"- _{hidden} more unended job(s) ({whose}, exited or killed): `ddflow job list` "
            "shows them; `ddflow job end` records each one collected._"
        )
    out.append("")


def _brief_memories(out: list[str], memories: list) -> None:
    """Operational facts about this machine and repository, newest first.

    After the binding decisions and before the advice: a memory is what the source
    projects' agents were required to read FIRST every session ("this box has 8 H200s",
    "a uniform-zero eval usually means a sidecar 404"), and it costs the next agent a day
    to re-learn one. Said to be partial when it is, so a truncated list is not read as
    the whole store.
    """
    if not memories:
        return
    out += ["", "## Operational memory", "", "_Facts about this machine and repository._", ""]
    for m in memories:
        when = clock.fmt_date(m.origin_at or m.at)
        fenced = PV.fence("memory", m.id, m.text, PV.memory_origin(m))
        out.append(f"- {fenced}  `[{m.id}{' ' + when if when else ''}]`")


def _brief_lessons(out: list[str], cfg: Config, lessons: list[dict], state: State) -> None:
    if not lessons:
        return
    out += [
        "",
        "## Lessons that bear on this task",
        "",
        "_Ranked against the task text, not by recency._",
        "",
    ]
    for ls in lessons:
        rule = (ls.get("rule") or "")[: cfg.lessons.snippet_chars]
        rec = state.lessons.get(ls.get("id", ""))
        origin = PV.lesson_origin(rec) if rec else PV.Origin(PV.UNKNOWN)
        out.append(
            "- "
            + PV.fence("lesson", ls.get("id", ""), f"**{ls.get('title', '')}** — {rule}", origin)
        )


def _brief_skills(out: list[str], skills: list) -> None:
    if not skills:
        return
    out += [
        "",
        "## Project skills and rules that bear on this task",
        "",
        "_The project's own; ranked against the task text. Read the file, do not rely on this line._",
        "",
    ]
    out += [e.line() for e in skills]


#: Each section's share of the brief's budget, in the brief's order, when the whole does
#: not fit (B1472311a63). Cutting from the bottom alone let any long section -- other
#: items' jobs, leftovers, blocked items, eight decisions of 7309 characters -- take the
#: space of everything after it, so the rules and lessons never reached the agent. A
#: section that needs less leaves the rest to the sections that need more, in proportion
#: to their shares.
_SECTION_SHARE: dict[str, float] = {
    "recovery": 0.10,
    "jobs": 0.05,
    "current": 0.20,
    "ready": 0.12,
    "decisions": 0.25,
    "memories": 0.08,
    "rules": 0.02,
    "lessons": 0.15,
    "skills": 0.03,
}

#: Where the rest of a trimmed section is.
_SECTION_MORE: dict[str, str] = {
    "recovery": "`ddflow recover`",
    "jobs": "`ddflow job list`",
    "current": "`ddflow show {item}`",
    "ready": "`ddflow next`",
    "decisions": "`ddflow decision applicable {item}`",
    "memories": "`ddflow memory list`",
    "rules": "the rules file",
    "lessons": "`ddflow recall <topic>`",
    "skills": "`ddflow recall <topic>`",
}

#: The words a trimmed section ends with.
SECTION_TRIMMED = "cut to fit session.brief_max_tokens"

#: The least a section is allowed when trimmed: its heading and a line or two.
_SECTION_FLOOR = 160
#: How many left-out records a trimmed section names; the rest are counted.
_SECTION_NAMED = 6


def _record_id(line: str) -> str:
    """The id of the fenced record a brief line quotes, "" for none."""
    m = re.search(rf'<{PV.TAG} kind="[^"]*" id="([^"]*)"', line)
    return m.group(1) if m else ""


def _trim_section(name: str, lines: list[str], room: int, item: str) -> list[str]:
    """``lines`` cut at a line boundary to ``room`` characters, ending with one line that
    says how much is missing and where it is. Records left out are NAMED: an agent may
    not know a binding decision's text, but it must know the decision exists."""
    where = _SECTION_MORE.get(name, "`ddflow brief`").format(item=item or "<id>")
    kept: list[str] = []
    used = 0
    for i, line in enumerate(lines):
        rest = lines[i:]
        seen = {_record_id(k) for k in kept}
        ids = list(dict.fromkeys(r for r in map(_record_id, rest) if r and r not in seen))
        entries = sum(1 for ln in rest if ln.startswith("- ")) or len([ln for ln in rest if ln])
        named = f": {', '.join(ids[:_SECTION_NAMED])}" if ids else ""
        if len(ids) > _SECTION_NAMED:  # bounded: hundreds of ids would overrun the share
            named += f" and {len(ids) - _SECTION_NAMED} more"
        marker = f"- _[{entries} more {SECTION_TRIMMED}{named}; {where}]_"
        # The heading (and the blank lines around it) stays: a section cut to nothing
        # would read as a section with nothing in it.
        heading = not any(k.startswith("#") for k in kept) and (
            not line.strip() or line.startswith("#")
        )
        if used + len(line) + 1 + len(marker) + 1 > room and not heading:
            if any(ln.strip() for ln in rest):
                kept.append(marker)
            return kept
        kept.append(line)
        used += len(line) + 1
    return kept


def _allowances(sections: list[tuple[str, list[str]]], sizes: list[int], room: int) -> list[int]:
    """Each section's share of ``room``, raised to the floor, never more than it needs --
    and never more than ``room`` in all (critic): what the floors add is taken back from
    the sections above their floor, in proportion. Floors that cannot all fit fall back to
    the plain shares, which sum to ``room``."""
    want = [
        min(size, max(int(room * _SECTION_SHARE.get(name, 0.05)), _SECTION_FLOOR))
        for (name, _), size in zip(sections, sizes, strict=True)
    ]
    over = sum(want) - room
    if over <= 0:
        return want
    spare = [w - min(size, _SECTION_FLOOR) for w, size in zip(want, sizes, strict=True)]
    if sum(spare) < over:
        return [
            min(size, int(room * _SECTION_SHARE.get(name, 0.05)))
            for (name, _), size in zip(sections, sizes, strict=True)
        ]
    total = sum(spare)
    return [w - -(-over * sp // total) for w, sp in zip(want, spare, strict=True)]


def _fit_sections(
    sections: list[tuple[str, list[str]]], room: int, item: str
) -> tuple[list[str], bool]:
    """The sections joined, each trimmed to its share when the whole exceeds ``room``
    characters. Returns the lines and whether anything was cut."""
    sizes = [len("\n".join(lines)) + 1 if lines else 0 for _, lines in sections]
    if sum(sizes) <= room:
        return [line for _, lines in sections for line in lines], False
    allow = _allowances(sections, sizes, room)
    slack = room - sum(allow)
    # What one section leaves goes to those that still want more, by share; a section
    # that gets all it wants returns the rest to the pool for another pass.
    while slack > 0:
        wanting = [i for i, size in enumerate(sizes) if size > allow[i]]
        if not wanting:
            break
        weight = sum(_SECTION_SHARE.get(sections[i][0], 0.05) for i in wanting)
        given = 0
        for i in wanting:
            share = _SECTION_SHARE.get(sections[i][0], 0.05) / weight
            extra = min(sizes[i] - allow[i], max(1, int(slack * share)), slack - given)
            allow[i] += extra
            given += extra
        slack -= given
    out: list[str] = []
    trimmed = False
    for (name, lines), size, room_i in zip(sections, sizes, allow, strict=True):
        if size <= room_i:
            out += lines
        else:
            out += _trim_section(name, lines, room_i, item)
            trimmed = True
    return out, trimmed


def brief(  # noqa: PLR0913 -- each section's input, all keyword-only; held/suggested decide the heading
    state: State,
    cfg: Config,
    plan: Plan,
    *,
    repo: Path | None = None,
    item: str = "",
    lessons: list[dict] | None = None,
    skills: list | None = None,
    rules: str = "",
    recovery: list | None = None,
    decisions: list | None = None,
    memories: list | None = None,
    held: list[str] | None = None,
    suggested: bool = False,
    reserve: int = 0,
    loops: list | None = None,
    agent: str = "",
) -> str:
    """The session-start pack, under ``session.brief_max_tokens``.

    Ordered by what an agent must not miss: anything needing rescue first, then what
    it is doing, then what it may do next, then the lessons that bear on it. When the
    whole does not fit, each section is cut to its share of the budget
    (``_SECTION_SHARE``, B1472311a63) and says what it left out and where it is; what a
    short section does not use goes to the ones after it, head first, so the
    safety-critical head still survives a squeeze -- and no section ahead of them can
    cut the decisions, rules and lessons out. Cutting from the bottom remains only as
    the backstop.
    """
    sections: list[tuple[str, list[str]]] = [(name, []) for name in _SECTION_SHARE]
    part = dict(sections)
    _brief_recovery(part["recovery"], recovery or [])
    _brief_jobs(part["jobs"], state, item, agent)
    if item:
        _brief_current(
            part["current"], state, cfg, item, repo, held=held, suggested=suggested, loops=loops
        )
    _brief_ready(part["ready"], plan)
    _brief_decisions(part["decisions"], decisions or [])
    # `memories` is every LIVE one, newest first; how many to show is this view's call.
    shown = (memories or [])[: cfg.memory.brief_items]
    _brief_memories(part["memories"], shown)
    if shown and len(memories or []) > len(shown):
        part["memories"].append(
            f"- _{len(memories or []) - len(shown)} more: `ddflow memory list`, or "
            f"`ddflow recall <topic>`._"
        )
    if rules:
        part["rules"] += ["", "## Project rules", "", rules.strip()]
    _brief_lessons(part["lessons"], cfg, lessons or [], state)
    _brief_skills(part["skills"], skills or [])

    head: list[str] = ["# ddflow brief", ""]
    if any(PV.TAG in line for _, lines in sections for line in lines):
        head[1:1] = [f"_{PV.DATA_RULE}_", ""]
    # `reserve`: tokens a caller will PREPEND (the new-reports block), so the whole stays
    # inside the budget and it is the bottom that gives way.
    budget = max(1, cfg.session.brief_max_tokens - reserve)
    note = (
        f"\n\n_[brief truncated at {budget} tokens "
        f"(session.brief_max_tokens); `ddflow show <id>` for detail]_"
    )
    room = budget * 4 - len("\n".join(head)) - len(note) - 1
    body, trimmed = _fit_sections(sections, room, item)
    text = "\n".join(head + body)
    # The backstop, for a heading that alone overran its share: the note counts too.
    if len(text) + (len(note) if trimmed else 0) > budget * 4:
        text = text[: max(0, budget * 4 - len(note))].rsplit("\n", 1)[0]
        trimmed = True
    if trimmed:
        text += note
    return text


#: Every generated view: its filename and how to render it. The ONE map. There were two
#: -- this function's and a copy in `sessions.bundle` whose docstring said it used this
#: one -- and the copy already wrote different bytes. The pre-commit check
#: (`services/enforce.py::check_views`) reads it too, so a view added here is checked
#: without anyone remembering to.
VIEWS: tuple[tuple[str, Callable[[State, Config | None], str]], ...] = (
    ("QUEUE.md", board),
    ("LESSONS.md", lessons_md),
    ("LESSONS-SUMMARY.md", lessons_summary_md),
    ("RESEARCH.md", research_md),
)


def render_views(state: State, cfg: Config | None = None) -> dict[str, str]:
    """filename -> the exact text a view file must hold for this state."""
    return {name: fn(state, cfg).rstrip() + "\n" for name, fn in VIEWS}


def write_views(
    root: Path, state: State, cfg: Config | None = None, *, subdir: str = "docs/ddflow"
) -> list[Path]:
    """Regenerate every human view. Same state in, same bytes out -- which the commit
    hook now HOLDS it to (B18): a staged view that differs from this is refused."""
    d = Path(root) / subdir
    d.mkdir(parents=True, exist_ok=True)
    written = []
    for name, new in render_views(state, cfg).items():
        p = d / name
        if not p.exists() or p.read_text("utf-8") != new:
            p.write_text(new, "utf-8")
        written.append(p)
    return written
