"""Human-readable projections: boards, lessons, and the session brief.

Every file this module writes is **generated** and carries a header saying so. None is
ever parsed back. That single rule removes the entire failure family the projects that
inspired Orchard spent years fighting: markdown that is simultaneously a human document
and a machine record drifts, because humans edit prose and machines edit structure, and
neither notices the other. Here the log is the record and the markdown is a view, so a
stale view is repaired by regenerating it, never by reconciling it.

``brief`` is the load-bearing one. An agent starting a session needs the rules that
apply, the task at hand, and the handful of past lessons that bear on it — and needs
them in roughly a thousand tokens, not the fifteen thousand that reading the corpora
costs. It is retrieval, budgeted, with the budget enforced rather than hoped for.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from ..config import Config
from ..core.model import ABANDONED, BLOCKED, DONE, OUTCOME_MARK, RUNNING, State
from ..core.schedule import Plan, critical_path

GENERATED = (
    "<!-- GENERATED by `orchard render`. Do not edit: the event log is the source of truth. -->"
)

# Marks come from model.OUTCOME_MARK -- the board and the gate-status view must agree,
# and two copies of a lookup table are two copies that drift.


def _bar(done: int, total: int, width: int = 18) -> str:
    if total == 0:
        return "─" * width
    filled = round(width * done / total)
    return "█" * filled + "░" * (width - filled)


def _depth(state: State, item, root: str) -> int:
    """How far below the phase this item sits. Bounded, because a parent chain is
    operator-authored and a cycle in it must not hang the renderer."""
    depth, node, seen = 0, item, set()
    while node.parent and node.parent != root and node.parent not in seen:
        seen.add(node.id)
        node = state.items.get(node.parent)
        if node is None:
            break
        depth += 1
    return min(depth, 6)


def _nested(state: State, phase: str) -> list:
    """Tasks under a phase, each sub-task immediately after its parent."""
    tasks = state.tasks(phase)
    by_parent: dict[str, list] = {}
    for t in tasks:
        by_parent.setdefault(t.parent, []).append(t)
    out: list = []

    def walk(parent: str, seen: set) -> None:
        for t in sorted(by_parent.get(parent, []), key=lambda x: (x.priority, x.id)):
            if t.id in seen:
                continue
            seen.add(t.id)
            out.append(t)
            walk(t.id, seen)

    walk(phase, set())
    # Anything whose parent chain does not reach the phase (an orphan, or a cycle)
    # still belongs on the board: silently dropping it is how work disappears.
    listed = {t.id for t in out}
    out.extend(t for t in tasks if t.id not in listed)
    return out


def board(state: State, cfg: Config | None = None, *, phase: str = "") -> str:
    """The whole queue as a markdown board.

    The gate column is built from the CONFIGURED pipeline. It used to re-type the ten
    default gate ids, so a project that trimmed `gates.task_pipeline` to three got ten
    columns, seven of them permanently blank, under a caption naming gates it does not
    run. Passing `cfg=None` falls back to the defaults for callers that genuinely have
    no config to hand.
    """
    from ..services.gates import pipeline_for

    out = [GENERATED, "", "# Work queue", ""]
    phases = [p for p in state.phases() if not phase or p.id == phase]
    if not phases:
        out.append("_No phases yet. `orchard phase add <id> --title '...'`_")
        return "\n".join(out)
    for ph in sorted(phases, key=lambda p: (p.priority, p.id)):
        # Ordered so a sub-task follows its parent, and indented by depth: a flat list
        # of "P1.T1, P1.T1a, P1.T1b" hides that two of them are halves of the first.
        tasks = _nested(state, ph.id)
        # Abandoned tasks are SETTLED, not outstanding. Counting them in the
        # denominator made a completed phase render as "3/4 tasks", which reads as
        # unfinished work that no longer exists.
        abandoned = [t for t in tasks if t.state == ABANDONED]
        live = [t for t in tasks if t.state != ABANDONED]
        done = sum(1 for t in live if t.state == DONE)
        out.append(f"## {ph.id} — {ph.title or '(untitled)'}")
        out.append("")
        bits = [f"`{ph.state}`", f"{_bar(done, len(live))} {done}/{len(live)} tasks"]
        if abandoned:
            bits.append(f"{len(abandoned)} abandoned")
        if ph.needs:
            bits.append("needs " + ", ".join(f"`{n}`" for n in ph.needs))
        if ph.lease:
            bits.append(f"held by **{ph.lease.holder}**")
        out.append(" · ".join(bits))
        out.append("")
        if ph.body:
            out.append(textwrap.indent(ph.body.strip(), "> "))
            out.append("")
        if tasks:
            out.append("| | Task | State | Needs | Globs | Gates | Owner |")
            out.append("|---|---|---|---|---|---|---|")
            for t in tasks:
                mark = {DONE: "x", RUNNING: "~", BLOCKED: "!", ABANDONED: "-"}.get(t.state, " ")
                pipeline = (
                    pipeline_for(t, cfg) if cfg is not None else list(Config().gates.task_pipeline)
                )
                gates = "".join(OUTCOME_MARK.get(t.gate_outcome(g), " ") for g in pipeline)
                indent = "&nbsp;&nbsp;&nbsp;&nbsp;" * _depth(state, t, ph.id)
                out.append(
                    f"| [{mark}] | {indent}**{t.id}** {t.title} | {t.state} | "
                    f"{', '.join(t.needs) or '—'} | {', '.join(f'`{g}`' for g in t.globs) or '—'} | "
                    f"`{gates}` | {t.lease.holder if t.lease else '—'} |"
                )
            out.append("")
            caption = " · ".join(
                pipeline_for(tasks[0], cfg)
                if cfg is not None
                else list(Config().gates.task_pipeline)
            )
            out.append(
                f"<sub>Gate column order: {caption}. "
                "`x` passed `!` failed `?` unavailable `~` partial `-` skipped</sub>"
            )
            out.append("")
    cp = critical_path(state, phase)
    if len(cp) > 1:
        out.append(
            f"**Critical path** ({len(cp)} deep — this, not the task count, "
            f"sets the wall-clock floor): " + " → ".join(f"`{c}`" for c in cp)
        )
        out.append("")
    return "\n".join(out)


def lessons_md(state: State) -> str:
    out = [GENERATED, "", "# Lessons", ""]
    live = [x for x in state.lessons.values() if not x.superseded_by]
    if not live:
        out.append("_None recorded._")
        return "\n".join(out)
    by_tag: dict[str, list] = {}
    for ls in sorted(live, key=lambda x: x.at, reverse=True):
        for tag in ls.tags or ["untagged"]:
            by_tag.setdefault(tag, []).append(ls)
    for tag in sorted(by_tag):
        out.append(f"## {tag}")
        out.append("")
        for ls in by_tag[tag]:
            out.append(f"### {ls.title}")
            out.append("")
            out.append(f"**Rule.** {ls.rule}")
            if ls.why:
                out.append("")
                out.append(f"**Why.** {ls.why}")
            if ls.how:
                out.append("")
                out.append(f"**How to apply.** {ls.how}")
            if ls.seen_in:
                out.append("")
                out.append(f"**Seen in:** {', '.join(ls.seen_in)}")
            out.append("")
    return "\n".join(out)


def research_md(state: State) -> str:
    out = [
        GENERATED,
        "",
        "# Research log",
        "",
        "Every entry carries a verdict. An entry with no CONFIRMED or REFUTED label",
        "is a literature summary, not research, and is labelled THEORETICAL.",
        "",
    ]
    if not state.research:
        out.append("_None recorded._")
        return "\n".join(out)
    for r in sorted(state.research.values(), key=lambda x: x.at, reverse=True):
        out.append(f"## {r.question or r.id}")
        out.append("")
        out.append(f"**Verdict: {r.verdict}**" + (f" · item `{r.item}`" if r.item else ""))
        out.append("")
        for label, val in (
            ("Claim", r.claim),
            ("Mechanism", r.mechanism),
            ("Falsifier", r.falsifier),
            ("Budget", r.budget),
        ):
            if val:
                out.append(f"- **{label}.** {val}")
        if r.probe:
            out.append("")
            out.append("**Probe:**")
            out.append("")
            out.append("```console")
            out.append(f"$ {r.probe}")
            if r.probe_output:
                out.append(r.probe_output.rstrip())
            out.append("```")
        if r.sources:
            out.append("")
            out.append("**Sources:** " + ", ".join(r.sources))
        out.append("")
    return "\n".join(out)


def _approx_tokens(text: str) -> int:
    """Cheap token estimate: ~4 chars per token. Good enough to enforce a budget, and
    it costs no dependency — a tokenizer import here would make the brief the slowest
    command in the tool."""
    return max(1, len(text) // 4)


def _brief_recovery(out: list[str], recovery: list) -> None:
    if not recovery:
        return
    out += [
        "## ⚠ Recoverable work found",
        "",
        "Handle these BEFORE starting anything new — a crashed agent's worktree often",
        "holds finished work that exists nowhere else.",
        "",
    ]
    out += [f"- **{r.item}** ({r.kind}, was {r.holder}): {r.advice}" for r in recovery[:5]]
    out.append("")


def _brief_current(
    out: list[str], state: State, cfg: Config, item: str, repo: Path | None = None
) -> None:
    from ..services.gates import pipeline_for

    it = state.items.get(item)
    if not it:
        return
    out += [f"## Current: {it.id} — {it.title}", ""]
    out.append(
        f"- kind `{it.kind}` · state `{it.state}`"
        + (f" · held by `{it.lease.holder}`" if it.lease else "")
    )
    if it.needs:
        out.append("- needs: " + ", ".join(f"`{n}`" for n in it.needs))
    if it.globs:
        out.append("- writes: " + ", ".join(f"`{g}`" for g in it.globs))
    if it.worktree:
        # Resolved for display: a relative path is portable in the LOG and ambiguous in
        # a brief, where the reader is about to `cd` to it.
        from ..infra.worktree import load_path

        out.append(
            f"- worktree: `{load_path(repo, it.worktree) if repo else it.worktree}`"
            f" on `{it.branch}`"
        )
    todo = [g for g in pipeline_for(it, cfg) if it.gate_outcome(g) not in ("passed", "skipped")]
    out.append("- gates remaining: " + (" → ".join(todo) if todo else "none — ready to complete"))
    if it.body:
        out += ["", textwrap.indent(it.body.strip()[:700], "> ")]
    out.append("")


def _brief_ready(out: list[str], plan: Plan) -> None:
    out += ["## Ready now", ""]
    if plan.ready:
        for r in plan.ready:
            out.append(
                f"- **{r.id}** — {r.title}" + (f" (writes {', '.join(r.globs)})" if r.globs else "")
            )
        if len(plan.ready) > 1:
            out += [
                "",
                f"These {len(plan.ready)} are independent: they can run in parallel worktrees.",
            ]
    else:
        out.append("_Nothing ready._")
    if plan.blocked:
        out += ["", "## Blocked (and why)", ""]
        out += [f"- `{b.item}` — {b.reason}: {b.detail}" for b in plan.blocked[:6]]


def _brief_decisions(out: list[str], decisions: list) -> None:
    """Architectural decisions governing the current item's files.

    Placed ABOVE lessons on purpose: a decision is binding and a lesson is advice, and
    an agent skimming a brief should meet the binding thing first. Surfaced by glob
    match rather than by search, so a decision reaches whoever is about to write the
    code it governs without their having to suspect it exists.
    """
    if not decisions:
        return
    out += [
        "",
        "## Architectural decisions governing these files",
        "",
        "_Binding unless the operator says otherwise. A superseded decision names "
        "its replacement — follow the replacement._",
        "",
    ]
    for d in decisions:
        line = f"- **{d.title}** — {d.decision}"
        if d.superseded_by:
            line += f"  ⚠ SUPERSEDED by {d.superseded_by}"
        out.append(line)
        if d.alternatives:
            out.append(f"  - rejected: {d.alternatives[:160]}")


def _brief_lessons(out: list[str], cfg: Config, lessons: list[dict]) -> None:
    if not lessons:
        return
    out += [
        "",
        "## Lessons that bear on this task",
        "",
        "_Ranked against the task text, not by recency._",
        "",
    ]
    for ls in lessons:
        rule = (ls.get("rule") or "")[: cfg.lessons.snippet_chars]
        out.append(f"- **{ls.get('title', '')}** — {rule}")


def brief(
    state: State,
    cfg: Config,
    plan: Plan,
    *,
    repo: Path | None = None,
    item: str = "",
    lessons: list[dict] | None = None,
    rules: str = "",
    recovery: list | None = None,
    decisions: list | None = None,
) -> str:
    """The session-start pack, under ``session.brief_max_tokens``.

    Ordered by what an agent must not miss: anything needing rescue first, then what
    it is doing, then what it may do next, then the lessons that bear on it. The budget
    is enforced by truncating from the BOTTOM, so the safety-critical head survives a
    squeeze -- which is why the section order is a correctness property, not layout.
    """
    out: list[str] = ["# Orchard brief", ""]
    _brief_recovery(out, recovery or [])
    if item:
        _brief_current(out, state, cfg, item, repo)
    _brief_ready(out, plan)
    _brief_decisions(out, decisions or [])
    if rules:
        out += ["", "## Project rules", "", rules.strip()]
    _brief_lessons(out, cfg, lessons or [])

    text = "\n".join(out)
    budget = cfg.session.brief_max_tokens
    if _approx_tokens(text) > budget:
        text = text[: budget * 4].rsplit("\n", 1)[0]
        text += (
            f"\n\n_[brief truncated at {budget} tokens "
            f"(session.brief_max_tokens); `orchard show <id>` for detail]_"
        )
    return text


def write_views(
    root: Path, state: State, cfg: Config | None = None, *, subdir: str = "docs/orchard"
) -> list[Path]:
    """Regenerate every human view. Idempotent: same state in, same bytes out."""
    d = Path(root) / subdir
    d.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in (
        ("QUEUE.md", board(state, cfg)),
        ("LESSONS.md", lessons_md(state)),
        ("RESEARCH.md", research_md(state)),
    ):
        p = d / name
        new = text.rstrip() + "\n"
        if not p.exists() or p.read_text("utf-8") != new:
            p.write_text(new, "utf-8")
        written.append(p)
    return written
